modules/disabling-applications-connected-to-open-data-hub.adoc
modules/enabling-services-connected-to-open-data-hub.adoc
modules/launching-jupyter-and-starting-a-notebook-server.adoc
modules/logging-in-to-open-data-hub.adoc
modules/notifications-in-open-data-hub.adoc
modules/options-for-notebook-server-environments.adoc
modules/removing-disabled-applications-from-open-data-hub.adoc
modules/supported-packages.adoc
modules/supported-services.adoc
modules/the-open-data-hub-user-interface.adoc
modules/tutorials-for-data-scientists.adoc
modules/updating-your-project-with-changes-from-a-remote-git-repository.adoc
modules/uploading-an-existing-notebook-file-from-a-git-repository-using-jupyterlab.adoc
modules/uploading-an-existing-notebook-file-from-a-git-repository-using-the-command-line-interface.adoc
modules/uploading-an-existing-notebook-file-from-local-storage.adoc

- This PR updates various modules in the _Getting started_ guide to make them suitable for downstream use in RHODS. 
- The primary updates were to:
-- Replace any direct references to "Open Data Hub" with a product name attribute (meaning that the name will be automatically replaced with "Red Hat OpenShift Data Science" downstream) 
-- Add conditional statements to control differences between ODH-only content and content for RHODS self-managed and cloud service. 
-- Update some module IDs to remove the ODH product name. If not, this appears in the URL and is unsuitable for use in RHODS.
- These updates have been verified by generating the ODH site locally and performing a side-by-side comparison of the updated content with the _Getting started_ guide currently published on the [Open Data …

DS-8911 Update some Getting Started modules for use downstream

---

modules/launching-jupyter-and-starting-a-notebook-server.adoc

removed obsolete warning from the getting started guide
In the Launching Jupyter and starting a notebook server, removed the warning note at the end of the procedure.
while investigating on https://issues.redhat.com/browse/RHODS-7718 they confirmed that this is not the case anymore.

install-guide-remove-warning

---

modules/logging-in-to-open-data-hub.adoc

remove obsolete note from Getting Started guide 
removed note about authorization from the Logging in to OpenShift Data Science section
as per RHODS-8024

get-start-remove-login-note

---

assemblies/creating-and-importing-notebooks.adoc
modules/notebook-images-for-data-scientists.adoc
modules/uploading-an-existing-notebook-file-from-a-git-repository-using-jupyterlab.adoc
modules/uploading-an-existing-notebook-file-from-a-git-repository-using-the-command-line-interface.adoc

- Update the 'Creating and importing notebooks' chapter based on comparison with [downstream](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science_self-managed/1-latest/html/working_on_data_science_projects/creating-and-importing-notebooks_notebooks).
- Verified with a local build of the Open Data Hub website.

DS-9749 Update 'Creating and importing notebooks' chapter based on comparison with downstream

---

modules/cloning-a-scheduled-pipeline-run.adoc

Added the word 'to' under 4.2.3. Cloning a scheduled pipeline run, step 8.
If you selected Schedule recurring run in the previous step, to configure the trigger type for the run, perform one of the following actions:

RHODS-12521: Correcting sentence in 4.2.3

---

modules/notifications-in-open-data-hub.adoc

Per team discussion, removing the following line from notifications-in-open-data-hub:
> Notification messages are displayed in the lower left corner of the Red Hat OpenShift Data Science interface when they are triggered.

RHODS-12364: Removing sentence on notification messages.

---

modules/overview-of-user-types-and-permissions.adoc

In the following sentence, 'OpenShift Data Science' is incorrect, and should just be OpenShift. 
>  If you decide to use specialized user groups without adding these groups from an identity provider, you must create the groups in OpenShift Data Science and then add the appropriate users to them. 
Checked with @chtyler, and replaced {productname-short}  with {openshift-platform}.

DS-12413: Correcting product name attribute.

---

_artifacts/document-attributes-global.adoc
assemblies/monitoring-models-for-bias.adoc
assemblies/support-requirements-and-limitations.adoc
assemblies/working-with-data-science-pipelines.adoc
modules/common-questions.adoc
modules/configuring-a-custom-notebook.adoc
modules/configuring-bias-monitoring-cli.adoc
modules/configuring-bias-monitoring-ui.adoc
modules/configuring-the-default-pvc-size-for-your-cluster.adoc
modules/disabling-applications-connected-to-open-data-hub.adoc
modules/enabling-services-connected-to-open-data-hub.adoc
modules/enabling-trustyai-service-cli.adoc
modules/installing-python-packages-on-your-notebook-server.adoc
modules/options-for-notebook-server-environments.adoc
modules/overview-of-pipelines-in-jupyterlab.adoc
modules/restoring-the-default-pvc-size-for-your-cluster.adoc
modules/supported-packages.adoc
modules/supported-services.adoc
modules/the-open-data-hub-user-interface.adoc
modules/troubleshooting-common-problems-in-jupyter-for-administrators.adoc
modules/troubleshooting-common-problems-in-jupyter-for-users.adoc
modules/tutorials-for-data-scientists.adoc
modules/viewing-bias-metrics.adoc
modules/viewing-the-performance-metrics-of-a-deployed-model.adoc
monitoring-data-science-models.adoc

Added the org-name attribute to use in place of 'Red Hat'. The new attribute includes a non-breaking space, per style guidance.

RHODS-12779: Adding a non-breaking space to 'Red Hat'

---

modules/troubleshooting-common-problems-in-jupyter-for-administrators.adoc

When files are deleted using the JupyterLab file explorer, they're actually moved to the user's local trash folder. This change adds a note advising users to delete the files from their local trash.

RHODS-5452: Adding delete trash note.

---

modules/deploying-a-model.adoc
modules/updating-the-deployment-properties-of-a-deployed-model.adoc

As per https://issues.redhat.com/browse/RHODS-10182, the **AWS_ prefix** no longer exists in the _define a new data connection dialog_. To address this, I've updated the labels of the data connections to remove the **AWS_prefix**, under the following sections:
- Deploying a model in Open Data Hub
- Updating the deployment properties of a deployed model
Validated with a local build of the Open Data Hub website.

RHODS-10182-Updating labels for data connections

---

modules/configuring-a-pipeline-server.adoc

As per https://issues.redhat.com/browse/RHODS-12944, the AWS_ prefix no longer exists in the `configure a pipeline` dialog. To address this, I've updated the labels of the data connections.
Validated with a local build of the Open Data Hub website.

Updating labels for pipeline data connection

---

modules/adding-a-model-server-to-your-data-science-project.adoc
modules/configuring-distributed-workloads.adoc
modules/launching-jupyter-and-starting-a-notebook-server.adoc
modules/options-for-notebook-server-environments.adoc
modules/troubleshooting-common-problems-in-jupyter-for-administrators.adoc
modules/updating-notebook-server-settings-by-restarting-your-server.adoc

Updated "Adding users" links to
{rhodsdocshome}{default-format-url}/managing_users/adding-users_user-mgmt
Updated "Enabling GPU support" links to
{rhodsdocshome}{default-format-url}/managing_resources/managing-cluster-resources_resource-mgmt#enabling-gpu-support_cluster-mgmt
Upstream only link, fixed "Launching Jupyter and starting a notebook server" link under Additional Resources in updating-notebook-server-settings-by-restarting-your-server.adoc

ds-12932 fix broken links

---

modules/adding-a-data-connection-to-your-data-science-project.adoc

As per https://issues.redhat.com/browse/RHODS-9559, the data connections section currently mentions that data can be stored in an AWS S3 bucket. I've updated the doc to reflect that data can be stored in **any S3-compatible object storage.**
Validated with a local build of the Open Data Hub website.

Updating AWS S3 storage references to S3-compatible storage

---

_artifacts/document-attributes-global.adoc
modules/habana-gaudi-integration.adoc
modules/installing-the-odh-operator-v1.adoc
modules/installing-the-odh-operator-v2.adoc
modules/upgrading-the-odh-operator-v1.adoc

Added an attribute for `minimum ocp version`, replaced occurrences of 4.11 and 4.12 with the new attribute.
Local build. Screenshots added below.

Adding attribute for ocp minimum version

---

assemblies/working-with-data-science-pipelines.adoc
modules/configuring-a-pipeline-server.adoc
modules/creating-a-project-workbench.adoc
modules/deploying-a-model-using-the-multi-model-serving-platform.adoc
modules/updating-the-deployment-properties-of-a-deployed-model.adoc

Remove "AWS" from field names and make S3 references generic instead of AWS-specific

RHODS-12832 generic S3 references rev2

---

modules/adding-users-to-specialized-data-science-user-groups.adoc
modules/revoking-user-access-to-jupyter.adoc

As per https://issues.redhat.com/browse/RHOAIENG-649, the current content under the section "Revoking access to Jupyter"  indicates that the user can still access Openshift AI once the steps to revoke access to Jupyter are followed. The steps involve removing the affected user from specialized user groups (rhods-users,rhods-admins). Once removed from a specialized user group, the user actually loses access to the dashboard and associated services. I've updated the content to reflect the same.
- Local build

Updating section to highlight that users lose access to dashboard

---

modules/deploying-a-model-using-the-multi-model-serving-platform.adoc

https://issues.redhat.com/browse/RHOAIENG-666
Attempting to add clarity concerning object storage in this module: Users need access to and use S3-compatible object storage for storing their datasets. The described procedure doesn't "create" a bucket but creates a data source connection to the bucket so that the model to be deployed can access datasets as needed. 
Local Build

Additional pre-requisites w.r.t S3-compatible storage

---

modules/accessing-notebook-servers-owned-by-other-users.adoc
modules/enabling-gpu-support-in-data-science.adoc
modules/starting-notebook-servers-owned-by-other-users.adoc

- Broken link in "Enabling GPU support in Openshift AI" was fixed with https://issues.redhat.com/browse/RHOAIENG-961
- Changed "replica set" to "replicaset"
- Fixed link in "Starting notebook servers owned by other users" and "Accessing notebook servers owned by other users" for Cloud Services docs

RHOAIENG-1444 fixes

---

assemblies/serving-large-language-models.adoc
assemblies/serving-small-and-medium-sized-models.adoc
modules/about-model-serving.adoc
modules/about-the-single-model-serving-platform.adoc
modules/accessing-api-endpoints-for-models-deployed-on-single-model-server.adoc
modules/adding-a-custom-model-serving-runtime.adoc
modules/adding-a-model-server-for-the-multi-model-serving-platform.adoc
modules/configuring-monitoring-for-the-single-model-serving-platform.adoc
modules/deploying-a-model-using-the-multi-model-serving-platform.adoc
modules/deploying-models-on-the-single-model-serving-platform.adoc
modules/deploying-models-using-the-single-model-serving-platform.adoc
modules/enabling-the-multi-model-serving-platform.adoc
modules/enabling-the-single-model-serving-platform.adoc
modules/installing-kserve.adoc
modules/updating-the-deployment-properties-of-a-deployed-model.adoc
modules/viewing-metrics-for-the-single-model-serving-platform.adoc
serving-models.adoc
working-on-data-science-projects.adoc

This PR covers the following:
- Contributing documentation for [serving large language models](https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_self-managed/2.5/html/working_on_data_science_projects/serving-large-language-models_serving-large-language-models) upstream
- Replicating changes to chapter on [serving small and medium-sized models](https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_self-managed/2.5/html/working_on_data_science_projects/serving-small-and-medium-sized-models_model-serving) upstream
- Adding both chapters to a new, standalone model serving guide
Changes verified via a local build of the Open Data Hub website.

DS-1808 Contribute updates to model-serving documentation upstream

---

modules/accessing-tutorials.adoc
modules/disabling-applications-connected-to-open-data-hub.adoc
modules/enabling-gpu-support-in-data-science.adoc
modules/enabling-services-connected-to-open-data-hub.adoc
modules/logging-in-to-open-data-hub.adoc
modules/removing-disabled-applications-from-open-data-hub.adoc
modules/troubleshooting-common-problems-in-jupyter-for-administrators.adoc
modules/troubleshooting-common-problems-in-jupyter-for-users.adoc

https://issues.redhat.com/browse/RHOAIENG-1540
Replacing {openshift-platform) attribute with plaintext Openshift for cloud service docs only. 
Local build upstream, also tested downstream, previews attached below:
**Upstream**
**Self-managed**
**Cloud Service (with cloud service attribute)**

RHOAIENG-1540: Updating OSD references upstream

---

modules/deploying-models-using-the-single-model-serving-platform.adoc

Amend note about using self-signed certs with KServe. There are now two possible actions that users can take, both documented in Solution articles.

Amend note about using self-signed certs with KServe

---

modules/accessing-notebook-servers-owned-by-other-users.adoc
modules/accessing-the-jupyter-administration-interface.adoc
modules/cleaning-up-after-deleting-users.adoc
modules/starting-notebook-servers-owned-by-other-users.adoc
modules/stopping-notebook-servers-owned-by-other-users.adoc

Updated the following sections of the managing users and managing resources guide to include references to ROSA, and also replace the _Adding administrative users in OSD_ to the _Adding administrative users in OpenShift_
Managing Users
- modules/cleaning-up-after-deleting-users.adoc
Managing Resources
-    modules/accessing-notebook-servers-owned-by-other-users.adoc
-    modules/accessing-the-jupyter-administration-interface.adoc
-    modules/starting-notebook-servers-owned-by-other-users.adoc
-    modules/stopping-notebook-servers-owned-by-other-users.adoc
Local Upstream build and downstream previews with ccutil.
Upstream Preview [UPDATED FEB 1]:
Downstream Previews:
[CS-Managing resources.pdf](https://github.com/opendatahub-io/opendatahub-documentation/files/14116607/CS-Managing.resource …

RHOAIENG-1916:Adding references to ROSA and updating links

---

modules/working-with-accelerator-profiles.adoc

I have removed the notice that the accelerator profiles feature is at tech preview from the "Working with accelerator profiles" page.

removed reference to accelerator profiles being at technology preview

---

modules/accessing-api-endpoints-for-models-deployed-on-single-model-server.adoc

Verified with local builds both upstream and downstream.  Downstream doesn't require explicit line breaks - this is handled nicely by our styling.
**Upstream**
**Downstream**

Break long code lines in upstream model serving docs

---

modules/about-the-single-model-serving-platform.adoc
modules/accessing-api-endpoints-for-models-deployed-on-single-model-server.adoc
modules/adding-a-custom-model-serving-runtime-for-the-single-model-serving-platform.adoc
modules/deploying-models-on-the-single-model-serving-platform.adoc
modules/enabling-the-single-model-serving-platform.adoc
modules/viewing-metrics-for-the-single-model-serving-platform.adoc

Adding OVMS runtime to single model serving docs
Local and downstream builds.

RHOAIENG-2828:Adding OVMS runtime to single model serving docs

---

assemblies/working-on-data-science-projects.adoc
modules/creating-a-data-science-project.adoc
modules/deploying-a-model-using-the-multi-model-serving-platform.adoc
modules/installing-odh-components.adoc
modules/sending-training-data-to-a-model.adoc
modules/viewing-a-deployed-model.adoc

conditionalized references to the TrustyAI/bias metrics feature so that they only appear in the upstream documentation.
References to the TrustyAI in the notebook image are not impacted

 remove-bias-references-2-19

---

modules/configuring-your-ide.adoc
modules/notebook-images-for-data-scientists.adoc
modules/options-for-notebook-server-environments.adoc

Adds entries for the RStudio Server and CUDA - RStudio Server notebook images in modules/notebook-images-for-data-scientists.adoc and modules/options-for-notebook-server-environments.adoc.

RHOAIENG-730: RStudio Server notebook images

---

assemblies/working-with-data-science-pipelines.adoc
modules/deleting-a-pipeline-server.adoc
modules/deleting-a-pipeline-version.adoc
modules/downloading-a-data-science-pipeline-version.adoc
modules/duplicating-a-scheduled-pipeline-run.adoc
modules/overview-of-pipeline-versions.adoc
modules/scheduling-a-pipeline-run.adoc
modules/uploading-a-pipeline-version.adoc
modules/viewing-pipeline-versions.adoc
modules/viewing-scheduled-pipeline-runs.adoc
modules/viewing-the-details-of-a-pipeline-version.adoc
modules/viewing-triggered-pipeline-runs.adoc

These changes contain documentation on data science pipeline versioning, to be available at RHOAI 2.7. 
These documentation changes have been tested against a build provided by the development team.

DS-2066-pipeline-versions initial draft of pipeline versions docs

---

modules/configuring-your-ide.adoc
modules/notebook-images-for-data-scientists.adoc
modules/options-for-notebook-server-environments.adoc

Adds a CUDA licensing note to where we reference the CUDA - RStudio image.

Adding CUDA licensing note.

---

modules/about-the-single-model-serving-platform.adoc
modules/deploying-models-on-the-single-model-serving-platform.adoc

In _Deploying models on the single model serving platform_ procedure, add a downstream note pointing to known issue RHOAIENG-3025 in the downstream release notes.
Verified with local build of ODH website.

DS-3025 Add downstream-only RN link

---

assemblies/serving-large-models.adoc
assemblies/serving-small-and-medium-sized-models.adoc
modules/adding-a-custom-model-serving-runtime-for-the-multi-model-serving-platform.adoc
modules/adding-a-custom-model-serving-runtime-for-the-single-model-serving-platform.adoc
modules/configuring-monitoring-for-the-multi-model-serving-platform.adoc
modules/configuring-monitoring-for-the-single-model-serving-platform.adoc
modules/viewing-metrics-for-the-multi-model-serving-platform.adoc

https://issues.redhat.com/browse/RHOAIENG-3761
RHOAIENG-3761: Add procedure for configuring monitoring  and viewing metrics on multi-model serving platform
Local upstream and downstream builds
#Previews
[Serving models self-managed preview.pdf](https://github.com/opendatahub-io/opendatahub-documentation/files/14462449/Serving.models.self-managed.preview.pdf)

RHOAIENG-3761: adding monitoring config and metrics viewing section for multi model

---

assemblies/working-with-data-science-pipelines.adoc
modules/scheduling-a-pipeline-run-using-a-cron-job.adoc

Added concept module to improve content on the supported cron format.

DS-587: Added concept module to improve content on the supported cron format

---

assemblies/customizing-the-dashboard.adoc
modules/ref-dashboard-configuration-options.adoc
modules/showing-hiding-information-about-enabled-applications.adoc

follow up to odh-766-mf 
updates found downstream

odh-766-mf-2 updates after downstream fetch 1

---

modules/configuring-a-pipeline-server.adoc

As per https://issues.redhat.com/browse/RHOAIENG-4279, 
- Need to document that an external database connection is secured by default
- Users must modify the DataSciencePiplinesApplication CR to connect to an unencrypted database.
Local build

RHOAIENG-4279: Adding note to external db connection section

---

assemblies/working-with-certificates.adoc
modules/using-certificates-with-data-science-pipelines.adoc
modules/using-certificates-with-workbenches.adoc

Adds component-specific self-signed certificate info for workbenches and pipelines.
- Adds a _Using self-signed certificates with {productname-short} components_ section to the _Working with certificates_ assembly.
- Adds two new modules to cover component-specific info for using self-signed certificates.
Note: The KCS article referenced in both new modules is still in progress, and will be completed in the next couple of days pre-release.

Adding component-specific self-signed cert info for IDE and Pipelines.

---

modules/configuring-a-pipeline-server.adoc

Adding navigation steps for modifying DSPA custom resource definition
local build

RHOAIENG-4279: Additional steps for updating DSPA crd

---

modules/configuring-your-ide.adoc

Adds a note to the Building the RStudio Server notebook images section, directing users to temp. workaround steps for the 2.8 RHOAI release.

Adds note and link to temp RStudio workaround steps.

---

modules/hiding-the-default-jupyter-application.adoc

addresses request by QE to mention that JupyterHub tile appears when you hide the Jupyter tile

odh-766-3-19 qe review comment

---

modules/deploying-models-using-the-single-model-serving-platform.adoc

**Changes**
- Modify wording about using a self-signed cert to deploy from S3-compatible storage
- Add upstream link
- Re-target downstream links
Changes validated with local build.

Add upstream link, modify wording, and re-target downstream links

---

modules/deploying-models-on-the-single-model-serving-platform.adoc

As per RHOAIENG-2082, adding bucket prerequisites to the procedure for deploying models on single-model serving platform. Also sneaked in hyphens for "single-model".
Local Build

RHOAIENG-2082: adding bucket prerequisites to single-model procedure

---

modules/using-certificates-with-data-science-pipelines.adoc

From 2.9 the dspa metadata.name used by dashboard is "dspa". 
This change updates steps to provide a CA bundle specifically for DSP witht he new name.

RHOAIENG-4508: Updating the dspa value.

---

modules/enabling-the-multi-model-serving-platform.adoc
modules/enabling-the-single-model-serving-platform.adoc
modules/viewing-http-request-metrics-for-a-deployed-model.adoc

Adding a few dashboard configuration options as prerequisites within the serving models section, where relevant.
https://issues.redhat.com/browse/RHOAIENG-4167
Local build

RHOAIENG-4167: adding dashboard options as prereqs

---

assemblies/serving-small-and-medium-sized-models.adoc
serving-models.adoc

The _Monitoring deployed models_ chapter under **Serving small and medium-sized models**  duplicates the _Monitoring model performance_ chapter under **Serving Models**.  This commit has the following changes:
- Removed the _Monitoring model performance_ chapter under **Serving Models**.
- Changed the title of the _Monitoring deployed models_ chapter to  _Monitoring model performance_ under the **Serving small and medium-sized models** section.
Local Build

RHOAIENG-4564: Moving model performance section under multi-model

---

modules/installing-odh-components.adoc

Adding the Authorino Operator to prerequisites for 2.x components installation.
The prerequisites don't mention the Authorino operator as a prerequisite. 
Once the ODH Operator is installed, though, the user is required (a UI banner asks for this) to create a `DSCInitialization` CR, which uses the Authorino operator and would fail if it is not installed.
Just displaying the rendered page.

Adding the Authorino Operator to prerequisites for 2.x components installation

---

modules/enabling-habana-gaudi-devices.adoc
modules/habana-gaudi-integration.adoc
modules/options-for-notebook-server-environments.adoc
modules/overview-of-accelerators.adoc

- Adds the 2024.1 versions for workbench images.
- Removes the 1.2 versions for workbench images and labels 2023.1 as 'Deprecated'.
- Updates the Habana version to 1.13, and updates various notes and resource sections to refer to both the 1.10 and 1.13 Habana operator versions.

2024a workbench image updates

---

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc

ENG-5345: Updates code comment and callout related to Ray security

ENG-5345: Updates code comment and callout for Ray security

---

assemblies/installing-odh-v2.adoc
assemblies/upgrading-odh-v2.adoc
modules/configuring-a-pipeline-server.adoc
modules/enabling-data-science-pipelines-2.adoc

- Updates the Argo Workflows installation and upgrade warnings to include specific info on the upgrade and install scenarios/resolution steps
- Adds warning about DSP 1.0 pipelines being inaccessible from the dashboard with DSP 2.0
- Adds prereq on MySQL DB version to _Configuring a pipeline server_
- Adds a note/warning to _Configuring a pipeline server_ about external MySQL DBs being migrated to DSP 2.0 format and becoming incompatible with earlier product versions.
- Updates note on storage directories in _Configuring a pipeline server_
- Adds a note to _Enabling DSP 2.0_ about the `PipelineConf` class being deprecated with no KFP 2.0 equivalent
- Adds info on how to identify Argo resources that were created by the product.

DSP 2.0 QE review updates

---

modules/viewing-metrics-for-the-multi-model-serving-platform.adoc
modules/viewing-metrics-for-the-single-model-serving-platform.adoc

RHOAIENG-4214: fixing links

---

assemblies/managing-applications-that-show-in-the-dashboard.adoc

I am reorganizing sections of the documentation.
Need to move these two modules to the Managing resources guide because they are relevant to admin users:
Disabling applications that are connected to OpenShift AI
Troubleshooting common problems in Jupyter

odh-7730 add two modules to managing resources guide

---

modules/configuring-the-operator-logger.adoc

Corrects downstream formatting, adds condition for upstream steps.

4156: Correcting formatting per ds review feedback.

---

modules/configuring-quota-management-for-distributed-workloads.adoc
modules/configuring-the-distributed-workloads-components.adoc
modules/running-distributed-data-science-workloads-disconnected-env.adoc
modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc
modules/running-distributed-data-science-workloads-from-notebooks.adoc

Added or changed text in 5 docs, which states that the end-user needs to have a data science project created in the prerequisites section of the instructions.

Added 'data science project' para to prerequisites x5 docs

---

modules/monitoring-distributed-workloads.adoc
modules/overview-of-distributed-workloads.adoc

Added a note about DSP workloads in 2 modules - related jira here:  https://issues.redhat.com/browse/RHOAIENG-3022

Added a note about DSP workloads in 2 modules

---

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc

ENG-7634: Updates pipeline example

ENG-7634: Updates pipeline example

---

modules/accessing-inference-endpoint-for-model-deployed-on-single-model-serving-platform.adoc

Removing references to TGIS gRPC API for vLLM
Local Build

RHOAIENG-5433: Removing references to TGIS gRPC API for vLLM

---

modules/configuring-quota-management-for-distributed-workloads.adoc
modules/configuring-the-distributed-workloads-components.adoc
modules/overview-of-kueue-resources.adoc
modules/running-distributed-data-science-workloads-disconnected-env.adoc

ENG-7635: Updates to clarify Red Hat support versus RHOAI support, and changes links to Kueue doc to link to new module instead

ENG-7635: Updates to clarify Red Hat support

---

modules/about-the-single-model-serving-platform.adoc

Clean up the wording to reflect that we are "configuring" not "installing" the dependencies.
Ran a local Gatsby build and verified that the changes appeared as expected

Adjust wording of installing Kserve

---

modules/about-the-single-model-serving-platform.adoc
modules/accessing-inference-endpoint-for-model-deployed-on-single-model-serving-platform.adoc
modules/enabling-the-single-model-serving-platform.adoc
modules/viewing-metrics-for-the-single-model-serving-platform.adoc

Update documentation to indicate that we now support the Caikit Standalone ServingRuntime. 
- Made updates and started local Gatsby build to preview doc page updates in my browser

Support for Caikit Standalone ServingRuntime

---

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc

For 2.11 the CodeFlare SDK will be supporting version 2.23.0 of Ray which will require a doc change to update the old image, from:  `quay.io/project-codeflare/ray:latest-py39-cu118` 
to the new one: `quay.io/rhoai/ray:2.23.0-py39-cu121`
Location in docs:
https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2-latest/html-single/working_with_distributed_workloads/index#running-distributed-data-science-workloads-from-ds-pipelines_distributed-workloads

image reference updated

---

modules/viewing-pipeline-step-logs.adoc

Adds a note highlighting that logging for python scripts running on Elyra pipelines will be changing in ODH2.14/RHOAI2.11.

7334 Elyra pipeline log changes

---

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc

ENG-8742: Updates pipeline example to remove workaround (for ENG-7346) added in PR 322

ENG-8742: Updates pipeline example to remove workaround

---

_artifacts/document-attributes-global.adoc
modules/accessing-notebook-servers-owned-by-other-users.adoc
modules/accessing-the-jupyter-administration-interface.adoc
modules/cleaning-up-after-deleting-users.adoc
modules/cleaning-up-resources.adoc
modules/installing-odh-components.adoc
modules/starting-notebook-servers-owned-by-other-users.adoc
modules/stopping-notebook-servers-owned-by-other-users.adoc

- Changed OpenShift Container Platform references in SM docs to {openshift-platform} where applicable
- Changed ROSA references in CS docs to ROSA Classic
- Other minor edits related to platform references

RHOAI-8083 platform references

---

assemblies/managing-cluster-resources.adoc
modules/overview-of-kueue-resources.adoc
modules/troubleshooting-common-problems-with-distributed-workloads-for-administrators.adoc
working-with-distributed-workloads.adoc

ENG-7652: Adds new DW troubleshooting modules to books

ENG-7652: Adds new DW troubleshooting modules to books

---

modules/configuring-monitoring-for-the-multi-model-serving-platform.adoc
modules/configuring-monitoring-for-the-single-model-serving-platform.adoc
modules/installing-odh-components.adoc
modules/viewing-metrics-for-the-multi-model-serving-platform.adoc
modules/viewing-metrics-for-the-single-model-serving-platform.adoc

Fixes links to the updated https://docs.openshift.com/container-platform/4.16/observability/monitoring/ section of the OCP docs, which previously was just /monitoring/.
- Updates some links to align with downstream changes
- Updates some links that I noticed also needed the same changes
Tested by previewing changes and confirming updated links work successfully.

Fixing links to updated OCP resources

---

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc

Removes the prerequisite that says you need to log in to RHOAI as a cluster-admin to perform the described task, as you do not.

Remove prerequisite about logging in as a cluster admin

---

modules/installing-odh-components.adoc

Added the step to create DSCInitialization when installing ODH.

Add create DSCInitialization step

---

examples/s3client_examples/s3client_examples.ipynb

- Adding an `examples` directory upstream to store code examples referenced in guides/tutorials.
- Also adding an S3 jupyter notebook that will be referenced in the updated S3 guide.

[Draft] RHOAIENG-664: Adding examples directory upstream

---

modules/running-distributed-data-science-workloads-disconnected-env.adoc

ENG-10137: Removes prereq and step about cert generation

ENG-10137: Removes prereq and step about cert generation

---

modules/running-distributed-data-science-workloads-from-notebooks.adoc

ENG-10447: Changes method to clone demo notebooks from CodeFlare SDK

ENG-10447: Changes method to clone demo notebooks

---

assemblies/serving-large-models.adoc
assemblies/serving-small-and-medium-sized-models.adoc
modules/viewing-http-request-metrics-for-a-deployed-model.adoc
modules/viewing-performance-metrics-for-deployed-model.adoc
modules/viewing-performance-metrics-for-model-server.adoc

Initial commit for KServe performance metrics feature.
- Adding a procedure for viewing kserve metrics on the single-model serving platform
Local build

RHOAIENG-4198: Initial commit for kserve perf metrics

---

assemblies/serving-large-models.adoc
modules/about-kserve-deployment-modes.adoc
modules/deploying-models-on-single-node-openshift-using-kserve-raw-deployment-mode.adoc

Documentation has been added on how to deploy models by using KServe Raw Deployment mode on single node OpenShift in a self-managed deployment only. By default, KServe uses the Red Hat Serverless mode, which is based on its open source Knative equivalent. However, you can also deploy models using raw deployment mode. The content explains the two modes, and why you would want to use them. 
There is also a procedure on how to deploy a model with raw deployment mode enabled. This procedure is mostly command-line based until UI support is added at a later date.

RHOAi-9793-10010 documented kserve rawdeployment steps

---

assemblies/serving-large-models.adoc
modules/optimizing-the-vllm-runtime.adoc

Adding procedure to configure speculative decoding and multi-modal inferencing for the vLLM runtime
Local Build

RHOAIENG-10023: Adding procedure for Speculative Decoding and Multi-Modal Inferencing

---

modules/viewing-metrics-for-the-single-model-serving-platform.adoc

Added a note explaining that metrics are only generated if an inference request is made.
Closes 9634
Built a local preview in Gatsby and confirmed changes appear

Add note about generating metrics for the vLLM runtime

---

assemblies/running-distributed-workloads.adoc
modules/downloading-the-demo-notebooks-from-the-codeflare-sdk.adoc
modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc
modules/running-distributed-data-science-workloads-from-notebooks.adoc

ENG-11839: Updates the download instructions for the demo notebooks

ENG-11839: Updates the download instructions for the demo notebooks

---

assemblies/monitoring-distributed-workloads.adoc
modules/configuring-quota-management-for-distributed-workloads.adoc
modules/monitoring-the-training-job.adoc
modules/running-the-training-job.adoc
modules/viewing-kueue-alerts-for-distributed-workloads.adoc

ENG-11059: Adds section about Kueue alerts

ENG-11059: Adds section about Kueue alerts

---

modules/ref-inference-endpoints.adoc

Adding note for chat_template requirement (RHOAIENG-12233)
```
As of vLLM v0.5.5, you must provide a chat template while querying a model using the /v1/chat/completions endpoint. If your model does not include a predefined chat template, you can use the chat-template command-line parameter to specify a chat template in your custom vLLM runtime, as shown in the example. Replace <CHAT_TEMPLATE> with the path to your template.
containers:
- args:
- --chat-template=<CHAT_TEMPLATE>
You can use the chat templates that are available as `.jinja` files link:https://github.com/opendatahub-io/vllm/tree/main/examples[here] or with the vLLM image under `/apps/data/template`. For more information about chat templates, see link:https://huggingface.co/docs/transformers/main/chat_templating[Chat …
```

RHOAIENG-13027: Adding note for chat_template requirement

---

modules/viewing-metrics-for-the-single-model-serving-platform.adoc

Not all commands to view metrics require prefixes. Removed text that implied all metrics commands required prefixes.
Made changes, built locally, and verified that changes appeared as expected

Remove specific prefixes

---

modules/adding-a-ca-bundle-after-upgrading.adoc
modules/adding-a-model-server-for-the-multi-model-serving-platform.adoc
modules/configuring-quota-management-for-distributed-workloads.adoc
modules/configuring-the-distributed-workloads-components.adoc
modules/deploying-models-on-the-single-model-serving-platform.adoc
modules/enabling-data-science-pipelines-2.adoc
modules/enabling-nvidia-gpus.adoc
modules/overview-of-kueue-resources.adoc
modules/understanding-certificates.adoc

Updated single-sourced downstream content in upstream repo to remove vernum refs in cloud docs.

updates to remove vernum ref in cloud doc instances

---

modules/overview-of-component-resource-customization.adoc

Updates the component deployment table in _Overview of component resource customization_ with new conditioning for model registry downstream.
+ Per discussion with component writers, updates to limit the TrustyAI component to upstream.

11031: Updating component resource customization table for MR TP.

---

modules/starting-a-workbench.adoc

- Updated workbench start/stop references to the button/link (instead of in the Actions menu)
- Verified that there are no references to an **Add storage** button on the Workbenches tab

Start/stop workbench UI update

---

modules/accessing-notebook-servers-owned-by-other-users.adoc
modules/accessing-the-jupyter-administration-interface.adoc

Reviewed prereqs of modules in the Managing resources book for RHOAI admin instead of cluster admin

Check Managing resources book for RHOAI admin

---

modules/deploying-models-on-the-single-model-serving-platform.adoc

If you have enabled GPUs on your cluster, you will be able to select and accelerator and set the number of accelerators to use on the "Deploy model" page for single-model serving. Adding this to the procedure.
Local build

RHOAIENG-15756: Adding accelerator step

---

modules/configuring-trustyai-with-a-database.adoc
modules/creating-a-bias-metric.adoc
modules/creating-a-drift-metric.adoc
modules/duplicating-a-bias-metric.adoc
modules/installing-trustyai-service-using-cli.adoc
modules/labeling-data-fields.adoc
modules/sending-training-data-to-trustyai.adoc

Downstream links were missing, since docs were previously only published upstream.

Adding downstream links

---

modules/adding-a-tested-and-verified-runtime-for-the-multi-model-serving-platform.adoc
modules/adding-a-tested-and-verified-runtime-for-the-single-model-serving-platform.adoc

Updating the YAML configuration for triton runtime to include newly tested models
Local build

RHOAIENG-16242: Updating YAML to include newly tested models

---

modules/ref-inference-endpoints.adoc

Adds a note to modules/ref-inference-endpoints.adoc, highlighting the REST endpoints that ModelMesh doesn't support.

Adding note highlighting endpoints not supported by ModelMesh

---

modules/deploying-models-on-the-NVIDIA-NIM-model-serving-platform.adoc
modules/enabling-the-nvidia-nim-model-serving-platform.adoc

Addressing SME/QE feedback:
- Removed model route options (applicable only to 2.17(
- Added that users need to enable single-model serving, but do not need to enable a preinstalled runtime.
- Added link to NVIDIA supported models
[NVIDIA_NIM.pdf](https://github.com/user-attachments/files/18594025/NVIDIA_NIM.pdf)
Local build

RHOAIENG-18466_rev1: Addressing SME/QE feedback

---

modules/enabling-intel-gaudi-ai-accelerators.adoc
modules/intel-gaudi-ai-accelerator-integration.adoc

This PR describes the steps to enable the Intel Gaudi AI Operator in ODH.

[DRAFT] ENG-16985 - documented gaudi operator upgrade steps

---

modules/deploying-model-stored-in-oci-image.adoc

The ID of modules/deploying-model-stored-in-oci-image.adoc doesn't match its title or filename. Updating to correct.
Checked for other instances of 'deploying-model-stored-in-oci-container' upstream and down, looks like just this one.

2161 link fixes: Correcting ID of oci image serving module

---

modules/configuring-the-model-registry-component.adoc

Removes a line from 2 notes in the modules/configuring-the-model-registry-component.adoc module, removing the requirement for prerequisite Operators to be installed in a specific order.

ENG-19276: Removing listed order Operator install req for model reg

---

assemblies/installing-odh-v2.adoc
modules/configuring-custom-namespaces.adoc
modules/installing-the-odh-operator-v2.adoc

Documentation on creating custom namespace before installing RHOAI.
Namespaces created by RHOAI tend to have “openshift”, “redhat”, etc, in their name. These namespaces should not be renamed because they are system namespaces and need the default name for RHOAI to function properly. 
However, customers want to install operators in custom-named namespaces. Renaming the namespace is particularly needed in Watsonx.ai. 
This feature would allow the customer to define a custom name when installing the operator namespace and DSCI.applicationNamespace, which are the two main use cases in customer requests for this feature.

[DRAFT]  - ENG-16992 custom namespace docs draft

---

modules/accessing-authorization-token-for-model-deployed-on-single-model-serving-platform.adoc
modules/accessing-inference-endpoint-for-model-deployed-on-single-model-serving-platform.adoc
modules/adding-a-model-server-for-the-multi-model-serving-platform.adoc
modules/deploying-model-stored-in-oci-image.adoc
modules/deploying-models-on-single-node-openshift-using-kserve-raw-deployment-mode.adoc
modules/deploying-models-on-the-NVIDIA-NIM-model-serving-platform.adoc
modules/deploying-models-on-the-single-model-serving-platform.adoc
modules/editing-the-deployment-properties-of-a-model-deployed-by-using-the-single-model-serving-platform.adoc
modules/making-inference-requests-to-models-deployed-on-single-model-server.adoc
modules/ref-inference-endpoints.adoc
modules/updating-a-model-server.adoc

The token **authorization** UI option has been updated to token **authentication**. Updating affected modules to reflect this change.
Local build

RHOAIENG-14622: Update references of token authorization to authentication

---

modules/creating-a-custom-training-image.adoc

ENG-19598: Removes reference to ray:2.35.0-py39-rocm62 file

ENG-19598: Removes reference to ray:2.35.0-py39-rocm62 file

---

assemblies/setting-up-trustyai-for-your-project.adoc
modules/sending-training-data-to-trustyai.adoc
modules/uploading-training-data-to-trustyai.adoc

Uploading Model Training Data module and references; 
Content (in modified format) from https://trustyai-explainability.github.io/trustyai-site/main/data-drift-monitoring.html#_upload_model_training_data_to_trustyai

Uploading Model Training Data module and references 

---

modules/adding-a-model-server-for-the-multi-model-serving-platform.adoc
modules/configuring-a-recommended-accelerator-for-notebook-images.adoc
modules/creating-a-hardware-profile.adoc
modules/creating-a-project-workbench.adoc
modules/deleting-a-hardware-profile.adoc
modules/deploying-models-on-the-NVIDIA-NIM-model-serving-platform.adoc
modules/deploying-models-on-the-single-model-serving-platform.adoc
modules/enabling-accelerators.adoc
modules/enabling-amd-gpus.adoc
modules/enabling-intel-gaudi-ai-accelerators.adoc
modules/enabling-nvidia-gpus.adoc
modules/importing-a-custom-workbench-image.adoc
modules/intel-gaudi-ai-accelerator-integration.adoc
modules/overview-of-accelerators.adoc
modules/updating-a-hardware-profile.adoc
modules/updating-a-model-server.adoc
modules/using-accelerators-with-vllm.adoc
modules/working-with-hardware-profiles.adoc
working-with-accelerators.adoc

This MR documents the introduction of hardware profiles, which acts as a superset of the accelerator profiles feature. Accelerator profiles will be officially deprecated at 2.19, yet will still appear in the UI by default until the GA of hardware profiles. Hardware profiles is tech preview at this release and is hidden behind a feature flag by default.

ENG-21266 initial draft of the hardware profile docs

---

modules/enabling-trustyai-component.adoc

Found a typo while going through the [docs](https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2.19/html/monitoring_data_science_models/configuring-trustyai_monitor):

Fix typo in enabling-trustyai-component.adoc

---

modules/creating-a-custom-training-image.adoc
modules/deploying-models-using-multiple-gpu-nodes.adoc
modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc
modules/running-the-demo-notebooks-from-the-codeflare-sdk.adoc

ENG-21369: Updates Ray image to 2.44.1 for Python 3.11

ENG-21369: Updates Ray image to 2.44.1 for Python 3.11

---

modules/creating-a-custom-training-image.adoc
modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc
modules/running-the-demo-jupyter-notebooks-from-the-codeflare-sdk.adoc

Updates Ray image to 2.46.0 for Python 3.11.
@coderabbitai ignore

ENG-26700: Updating Ray 2.44.1 > 2.46.0.

---

modules/adding-a-tested-and-verified-runtime-for-the-single-model-serving-platform.adoc
modules/customizable-model-serving-runtime-parameters.adoc
modules/ref-inference-endpoints.adoc
modules/ref-tested-verified-runtimes.adoc

@coderabbitai ignore
- Added Seldon MLServer to list of tested and verified runtimes
- Updated deployment procedure to include example yaml for Seldon MLServer
- Added link to MLServer model settings
- Added REST and gRPC inference endpoints and example commands
- Added note about alibi-detect and alibi-explain libraries, specifically to state that RH does not support them.
Local build
Added to tested and verified runtimes:
Inference endpoints:
Link to MLServer customizable paramters
Adding MLServer as a custom runtime:

RHOAIENG-26326:Adding Seldon MLServer

---

modules/creating-a-model-registry.adoc
modules/editing-a-model-registry.adoc

Adds a note about the need to add a CA certificate for the external database associated with your model registry instance if the DB is configured to enforce TLS.
@coderabbitai ignore

ENG-1840: Adding CA cert note to edit and create MR procs.

---

modules/adding-a-tested-and-verified-runtime-for-the-single-model-serving-platform.adoc
modules/ref-supported-runtimes.adoc
modules/ref-tested-verified-runtimes.adoc

Move the reference tables from the following two modules  to the Supported Configurations kbase article:
- Supported model-serving runtimes
- Tested and verified model-serving runtimes
   Fix a broken  link in the ref-tested-verified-runtimes module

odh-31309 move model-serving runtime ref info to kbase article

---

modules/deploying-models-on-single-node-openshift-using-kserve-raw-deployment-mode.adoc

Update the documentation to use the correct field name `rawDeploymentServiceConfig` as defined in the CRD specification.
**Jira:** [RHAIRFE-471](https://issues.redhat.com/browse/RHAIRFE-471)
The Red Hat OpenShift AI documentation shows an incorrect field name in the KServe configuration example:
- **Incorrect:** `RawDeploymentServiceConfig` (PascalCase)
- **Correct:** `rawDeploymentServiceConfig` (camelCase)
This causes users to get the error:
```
unknown field "RawDeploymentServiceConfig" in io.opendatahub.datasciencecluster.v1.DataScienceCluster.spec.components.kserve
```

Fix incorrect field name RawDeploymentServiceConfig in KServe documentation
