opendatahub-io/opendatahub-documentation

modules/disabling-applications-connected-to-open-data-hub.adoc, modules/launching-jupyter-and-starting-a-notebook-server.adoc, modules/the-open-data-hub-user-interface.adoc
- This PR updates various modules in the _Getting started_ guide to make them suitable for downstream use in RHODS. 
- The updates are based on downstream validation of content fetched from upstream.
- These updates have been verified by generating the ODH site locally and performing a side-by-side comparison of the updated content with the _Getting started_ guide currently published on the [Open Data Hub website](https://opendatahub.io/docs/getting-started-with-open-data-hub).
=> DS-8911_rev1 Single-sourcing updates for GS guide based on downstream testing

modules/enabling-services-connected-to-open-data-hub.adoc, modules/the-open-data-hub-user-interface.adoc
Minor content updates based on downstream validation.
=> DS-8911_rev2 Minor updates to GS

modules/enabling-services-connected-to-open-data-hub.adoc, modules/the-open-data-hub-user-interface.adoc
Update to Getting Started guide
minor changes - in UI section, updated the description of the Enabled button and clarification on what Enabled means
RHODS-8025
=>  get-start-enable-button

modules/launching-jupyter-and-starting-a-notebook-server.adoc
Quick update to an access permissions error message
=> getstart-fix-error-message

assemblies/working-with-data-science-pipelines.adoc, modules/enabling-services-connected-to-open-data-hub.adoc, modules/logging-in-to-open-data-hub.adoc, modules/overview-of-pipelines-in-jupyterlab.adoc, modules/supported-services.adoc, modules/viewing-scheduled-pipeline-runs.adoc, modules/viewing-the-performance-metrics-of-a-deployed-model.adoc, modules/viewing-triggered-pipeline-runs.adoc
address upstream mentions of OpenShift Data Science
=> ds-9500 fixing conditional text

modules/cloning-a-scheduled-pipeline-run.adoc, modules/configuring-a-pipeline-server.adoc
fixed two minor typos reported via DDF downstream
=> ds-9918-9919 ddf fixes

modules/configuring-access-to-data-science-projects.adoc
minor doc fix for DDF issue - explain what is meant by project details
=> ds-10001 define project details

common-questions.adoc, getting-started-with-open-data-hub.adoc
=> docs: DS-11789: Adds the common questions

assemblies/model-serving.adoc, assemblies/working-on-data-science-projects.adoc, modules/adding-a-custom-model-serving-runtime.adoc, modules/configuring-a-model-server-for-your-data-science-project.adoc, modules/updating-a-model-server.adoc
fixed typos "model sever" to "model server"
changed title of module and links from "Configuring a model server..." to "Adding a model server..." to reflect similar UI change
=> ds-11824 model server minor updates

common-questions.adoc, modules/common-questions.adoc
Further edits based on feedback in PR 25
=> docs: DS-11789: Moves common questions to correct location and edits content

modules/adding-a-custom-model-serving-runtime.adoc, modules/enabling-services-connected-to-open-data-hub.adoc, modules/troubleshooting-common-problems-in-jupyter-for-administrators.adoc
... and changes one occurrence of "configure" to "add" for consistency with other recent changes
=> docs: DS-11368: Updates OpenShift doclinks from 4.x to 4.13

modules/viewing-the-details-of-a-pipeline-run.adoc
very minor update to the module that mentions viewing the details of a scheduled pipeline run - can now view input parameters
=> ds-11821 pipeline run view input parameters

modules/updating-cluster-storage.adoc
doc update re: https://github.com/opendatahub-io/odh-dashboard/issues/1610
edited the "Updating cluster storage" module
=> ds-11823 update cluster storage

modules/options-for-notebook-server-environments.adoc
=> docs: DS-11788: Fixes doc typo

modules/accessing-notebook-servers-owned-by-other-users.adoc, modules/accessing-the-jupyter-administration-interface.adoc, modules/starting-notebook-servers-owned-by-other-users.adoc
fixing links and conditionalizing in the managing doc
=> ds-11812-3 fix conditions and links

modules/adding-users-to-specialized-data-science-user-groups.adoc, modules/stopping-notebook-servers-owned-by-other-users.adoc
Correcting typos and a link destination in Managing users and user resources.
- Corrected typos in _stopping-notebook-servers-owned-by-other-users.adoc_ and _adding-users-to-specialized-data-science-user-groups.adoc_.
=> RHODS-12425: Correcting issues in Managing users & user resources.

modules/options-for-notebook-server-environments.adoc
fixing a link for enabling gpu support
=> ds-11812-4 fixing link

modules/enabling-gpu-support-in-data-science.adoc
fix missing"in" in enabling GPU title
=> ds-11812-4b fix typo

modules/options-for-notebook-server-environments.adoc
updated versions in notebook server options
=> ds-12758 update notebook server options

modules/disabling-applications-connected-to-open-data-hub.adoc, modules/enabling-services-connected-to-open-data-hub.adoc, modules/the-open-data-hub-user-interface.adoc
Suggested updates from downstream MR.
=> RHODS-12777 MR updates.

modules/adding-a-model-server-to-your-data-science-project.adoc, modules/creating-a-project-workbench.adoc, modules/launching-jupyter-and-starting-a-notebook-server.adoc, modules/updating-a-model-server.adoc
Removing redundant 'Optional' label on accelerator steps, per MR feedback.
=> RHODS-12777_rev2: Removing redundant 'Optional' label.

modules/enabling-trustyai-service-cli.adoc
updated link to install doc - from the prerequisites in the enabling module in the Monitoring data models guide
=> ds-12760 update link to install doc

modules/enabling-trustyai-service-cli.adoc
as per https://github.com/trustyai-explainability/odh-trustyai-demos/blob/main/1-Installation/README.md#odh-v2x,
updated the oc apply command
=> ds-12760-2 update trustyai enable command

modules/adding-a-model-server-to-your-data-science-project.adoc, modules/enabling-gpu-support-in-data-science.adoc
fixing broken links - Nvidia reorganized their documentation
=> ds-12805 fix links to nvidia doc

modules/enabling-trustyai-service-cli.adoc
another edit to the enable trustyai module
=> ds-12760-4 update to enable trustyai module

modules/launching-jupyter-and-starting-a-notebook-server.adoc, modules/options-for-notebook-server-environments.adoc, modules/removing-disabled-applications-from-open-data-hub.adoc, modules/the-open-data-hub-user-interface.adoc
Some changes from PRs in the last week have been lost while we figured out working with the fetch script and requests in downstream MRs for changes to upstream content. 
This PR is to remake those lost changes, to align with downstream's up to date content.
=> RHODS-12833: Correcting lost changes.

modules/launching-jupyter-and-starting-a-notebook-server.adoc, modules/options-for-notebook-server-environments.adoc
Correcting capitalisation and wording.
=> RHODS-12833_rev1: Minor corrections

assemblies/installing-odh-v1.adoc, assemblies/installing-odh-v2.adoc, installing-open-data-hub.adoc, modules/accessing-the-odh-dashboard.adoc, modules/adding-an-odh-instance.adoc, modules/creating-a-new-project-for-your-odh-instance.adoc, modules/installing-odh-components.adoc, modules/installing-the-odh-operator-v1.adoc, modules/installing-the-odh-operator-v2.adoc
Initial add of install ODH files.
=> ds-12561 Install docs

modules/adding-a-model-server-to-your-data-science-project.adoc, modules/deploying-a-model.adoc, modules/enabling-gpu-support-in-data-science.adoc, modules/enabling-trustyai-service-cli.adoc
Correcting and adding some attribute instances.
=> Rhods 12779 rev1

modules/tutorials-for-data-scientists.adoc
Commenting out the line for SKLearn with canary deployment.
=> RHODS-12873: Update to Getting started doc 

_artifacts/document-attributes-global.adoc, modules/allocating-additional-resources-to-data-science-users.adoc, modules/backing-up-storage-data.adoc, modules/configuring-a-custom-notebook.adoc, modules/configuring-the-default-pvc-size-for-your-cluster.adoc, modules/creating-an-accelerator-profile.adoc, modules/deleting-an-accelerator-profile.adoc, modules/enabling-services-connected-to-open-data-hub.adoc, modules/enabling-trustyai-service-cli.adoc, modules/installing-odh-components.adoc, modules/restoring-the-default-pvc-size-for-your-cluster.adoc, modules/updating-an-accelerator-profile.adoc, modules/viewing-the-performance-metrics-of-a-deployed-model.adoc, modules/working-with-accelerator-profiles.adoc
RHODS-12872, update ocp-latest-version attribute to 4.14, replace 4.13 in links with attribute
=> ds-12872 ocp-latest-version 4.14

modules/upgrading-the-odh-operator.adoc
=> ds-12562 rev1, change window to dialog

modules/notebook-images-for-data-scientists.adoc, modules/options-for-notebook-server-environments.adoc
Updated the documentation to display the latest notebook image package versions and components. 
List was confirmed with QE representative and checked on a test cluster with an OAI 2.4 build.
=> Update relevant packages and components in documentation for OAI 2-4-0

assemblies/installing-odh-v2.adoc, assemblies/upgrading-odh-v1-to-v2.adoc, assemblies/upgrading-odh-v1.adoc, modules/upgrading-the-odh-operator-v1.adoc, upgrading-open-data-hub.adoc
Add upgrade-open-data-hub book and upgrade-odh-v1 assembly to match the install structure
=> ds-2562 rev2

assemblies/working-with-distributed-workloads.adoc, modules/overview-of-distributed-workloads.adoc, modules/running-distributed-data-science-workloads.adoc, modules/using-distributed-workloads.adoc
=> DS-12828: Adds first draft of 'Working with distributed workloads'

modules/creating-a-project-workbench.adoc
As per https://issues.redhat.com/browse/RHODS-12365, steps to add a data connection needed to be added to the workbench creation section: [Chapter 5. Creating a project workbench](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science_self-managed/1.33/html-single/getting_started_with_red_hat_openshift_data_science_self-managed/index#creating-a-project-workbench_get-started)
I've added the steps as required..
Validated with a local build of the Open Data Hub website. Preview of content attached below.
=> Adding data connection info to workbench config steps

modules/options-for-notebook-server-environments.adoc
Related to https://github.com/opendatahub-io/notebooks/pull/326
=> Update of Codeflare-SDK version in notebook pkg list

modules/configuring-bias-monitoring-cli.adoc, modules/viewing-bias-metrics.adoc
=> Ds 7642 11 27

assemblies/monitoring-models-for-bias.adoc, modules/configuring-bias-monitoring-cli.adoc
=> ds-7642-11-27-2 fix link 2

modules/accessing-notebook-servers-owned-by-other-users.adoc, modules/accessing-the-jupyter-administration-interface.adoc, modules/adding-a-model-server-to-your-data-science-project.adoc, modules/cleaning-up-after-deleting-users.adoc, modules/configuring-distributed-workloads.adoc, modules/enabling-gpu-support-in-data-science.adoc, modules/enabling-trustyai-service-cli.adoc, modules/launching-jupyter-and-starting-a-notebook-server.adoc, modules/options-for-notebook-server-environments.adoc, modules/overview-of-user-types-and-permissions.adoc, modules/revoking-user-access-to-jupyter.adoc, modules/starting-notebook-servers-owned-by-other-users.adoc, modules/stopping-notebook-servers-owned-by-other-users.adoc
=> Broken link fixes rev 2

modules/the-open-data-hub-user-interface.adoc
RHODS-11367 Add Settings > Serving runtimes
=> RHODS-11367 serving runtimes

assemblies/working-with-data-science-pipelines.adoc, modules/defining-a-pipeline.adoc
=> RHODS-12947 link fix

modules/options-for-notebook-server-environments.adoc
Updating package versions to align with latest.
=> RHODS-12818: Updating package versions.

modules/supported-services.adoc, modules/tutorials-for-data-scientists.adoc
Align supported ISVs in self-managed documentation with Dashboard
Getting started > 9.2 Supported services
- Change "Starburst Galaxy" to "Starburst Enterprise"
- Add ifndef::self-managed condition to Red Hat OpenShift API Management 
Getting started > 6. Tutorials for data scientists
- Change "Starburst Galaxy" to "Starburst Enterprise"
- Add ifndef::self-managed condition to Securing a deployed model using {org-name} OpenShift API Management
=> RHODS-7140 supported services

modules/accessing-the-odh-dashboard.adoc, modules/creating-a-project-workbench.adoc
As requested in https://issues.redhat.com/browse/RHODS-13009, replacing the word "data model" to "model". 
Validated with local build
=> Replacing the word "data model" with "model"

modules/supported-services.adoc, modules/tutorials-for-data-scientists.adoc
Getting started > 6. Tutorials for data scientists
- Remove NVIDIA GPU Quick start guides
- Add three new Starburst How to guides
=> RHODS-12942 tutorials

modules/enabling-trustyai-service-cli.adoc
https://issues.redhat.com/browse/RHODS-13077
Replaced **{productname-long} Operator** instances with plaintext **Red Had OpenShift Data Science**.
Local build, screenshots attached below.
=> RHODS-13077 Rebranding: updating references to operator 

modules/configuring-distributed-workloads.adoc
https://issues.redhat.com/browse/RHODS-13077
Replaced *{productname-long} Operator* instances with plaintext Red Had OpenShift Data Science.
local build, screenshots attached
=> RHODS-13077 Rebranding: updating references to operator

modules/options-for-notebook-server-environments.adoc
Updates a note in modules/options-for-notebook-server-environments.adoc to reflect latest product functionality.
=> RHODS-13080: Note update - Options for Notebook server environments

modules/supported-services.adoc, modules/tutorials-for-data-scientists.adoc
RHODS-7140 RHODS-12942 rev2 
Tutorials for data scientists:
Supported services:
Updates so Starburst Enterprise is SM only and Starburst Galaxy is Cloud only
=> RHODS-7140 RHODS-12942 rev2 tutorials

modules/accessing-notebook-servers-owned-by-other-users.adoc, modules/enabling-trustyai-service-cli.adoc, modules/starting-notebook-servers-owned-by-other-users.adoc, modules/stopping-notebook-servers-owned-by-other-users.adoc
Update to links to match new Pantheon titles, using attributes where possible
=> RHODS-13084 update links for new Pantheon titles

assemblies/monitoring-models-for-bias.adoc, modules/supported-bias-metrics.adoc
2.5 updates for trusty ai to address QE feedback
=> odh-797 trustyai update

modules/overview-of-user-types-and-permissions.adoc
Updates two links with the updated downstream module IDs.
=> Upstream rebranding2

modules/deleting-a-data-science-pipeline.adoc
Removing the productname attribute and correcting reference to the Data Science Pipelines page.
=> Updating reference to data science pipelines page.

modules/logging-in-to-open-data-hub.adoc
Updates the dashboard URL -it should still be 'rhods-dashboard'.
=> RHOAIENG-725: Correcting dashboard url.

_artifacts/document-attributes-global.adoc, modules/configuring-the-default-pvc-size-for-your-cluster.adoc, modules/defining-data-science-admin-and-user-groups.adoc, modules/restoring-the-default-pvc-size-for-your-cluster.adoc, modules/stopping-idle-notebooks.adoc
Adjusts references to user and admin groups so we're not using the productname attributes as names/labels. 
Updates the values of the oai-user-group and oai-admin-group attributes.
=> RHOAIENG-725: Updates for user and admin groups

modules/adding-users-to-specialized-data-science-user-groups.adoc, modules/overview-of-user-types-and-permissions.adoc, modules/revoking-user-access-to-jupyter.adoc, modules/troubleshooting-common-problems-in-jupyter-for-administrators.adoc, modules/troubleshooting-common-problems-in-jupyter-for-users.adoc, modules/viewing-data-science-users.adoc
Updating references to user and admin groups so we aren't using the product name attributes as labels.
=> User and admin group updates.

modules/configuring-bias-monitoring-cli.adoc
Fixing link to https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_self-managed/2.5/html/monitoring_data_science_models/monitoring-models-for-bias_bias-monitoring#supported-bias-metrics_bias-monitoring
=> RHOAIENG-938 fix link

modules/updating-a-model-server.adoc
Working on data science projects > 5.1.4. Updating a model server
Step 3, changed "The **Configure** model server dialog opens." to "The **Edit** model server dialog opens."
=> RHOAIENG-971 change Configure to Edit

assemblies/upgrading-odh-v1-to-v2.adoc
Removed note about Alpha release as the v2 operator is now GA
=> RHOAIENG-781 upgrading ODH

assemblies/monitoring-models-for-bias.adoc, modules/viewing-bias-metrics.adoc
Fix for broken link in
Monitoring data science models > Viewing bias metrics for a model
=> RHOAIENG-963 link fix

modules/configuring-bias-monitoring-cli.adoc, modules/configuring-bias-monitoring-ui.adoc, modules/enabling-trustyai-service-cli.adoc, modules/viewing-bias-metrics.adoc, modules/viewing-the-performance-metrics-of-a-deployed-model.adoc, monitoring-data-science-models.adoc
=> odh-962 fix broken link in TP note

modules/enabling-gpu-support-in-data-science.adoc
Managing resources > Enabling GPU support in Open Data Hub
- Add link to Working with accelerator profiles
=> RHOAIENG-961 add link to accelerator docs

modules/configuring-bias-monitoring-cli.adoc, modules/enabling-trustyai-service-cli.adoc
=> odh-683-12-20

modules/tutorials-for-data-scientists.adoc
=> odh-939 tutorial title change

modules/tutorials-for-data-scientists.adoc
=> odh-939-2 fix downstream link

modules/updating-the-deployment-properties-of-a-deployed-model.adoc
=> change Configure to Deploy

_artifacts/document-attributes-global.adoc, assemblies/installing-odh-v1.adoc, assemblies/installing-odh-v2.adoc, assemblies/upgrading-odh-v2.adoc, modules/cleaning-up-resources.adoc, modules/installing-the-odh-operator-v2.adoc, modules/overview-of-upgrading-odh.adoc, modules/requirements-for-upgrading-odh.adoc, upgrading-open-data-hub.adoc
Add new modules to upgrade process:
Overview of upgrading
Requirements for upgrading
=> RHOIENG-479 upgrade process info

modules/accessing-the-jupyter-administration-interface.adoc, modules/enabling-trustyai-service-cli.adoc, modules/stopping-notebook-servers-owned-by-other-users.adoc
Fix links in Cloud Services docs
=> RHOIENG-1417 link fix

modules/enabling-trustyai-service-cli.adoc
Updating UI operator to `Red Hat OpenShift AI`
=> Updating UI operator

modules/about-deleting-users-and-resources.adoc, modules/revoking-user-access-to-jupyter.adoc
- About deleting users and their resources - fixed typo in last bullet
- Revoking user access to Jupyter - added s to Workloads -> Pods
=> RHOAIENG-1444 Managing users typos

modules/adding-a-custom-model-serving-runtime.adoc, modules/adding-a-model-server-for-the-multi-model-serving-platform.adoc, modules/deploying-models-on-the-single-model-serving-platform.adoc, modules/deploying-models-using-the-single-model-serving-platform.adoc, modules/installing-kserve.adoc, modules/viewing-metrics-for-the-single-model-serving-platform.adoc
Ensure that all external links open in a new browser tab.
=> DS-1808_rev1 Link updates

modules/creating-a-bias-metric-using-cli.adoc, modules/creating-a-bias-metric-using-dashboard.adoc, modules/duplicating-a-bias-metric.adoc, modules/viewing-bias-metrics.adoc
=> RHAOIENG-779 downstream xrefs

modules/viewing-performance-metrics-for-model-server.adoc
=> odh-1886-4 fix link in monitoring performance models module

modules/accessing-notebook-servers-owned-by-other-users.adoc, modules/accessing-the-jupyter-administration-interface.adoc, modules/cleaning-up-after-deleting-users.adoc, modules/enabling-trustyai-service-using-cli.adoc, modules/enabling-trustyai-service-using-dashboard.adoc, modules/overview-of-user-types-and-permissions.adoc, modules/starting-notebook-servers-owned-by-other-users.adoc, modules/stopping-notebook-servers-owned-by-other-users.adoc
Updating links for new install/uninstall/upgrade book structures
=> RHOAIENG-1287 rev2 link updates

modules/running-distributed-data-science-workloads-disconnected-env.adoc
First draft of the new section:
"Running distributed data science workloads in a disconnected environment"
=> ENG-281: Adds new section (DW disconnected)

assemblies/working-with-distributed-workloads.adoc
Adds new files to the distributed workloads assembly
=> ENG-1789: Adds new files to assembly

assemblies/working-on-data-science-projects.adoc, modules/creating-a-data-science-project.adoc, modules/deploying-a-model-using-the-multi-model-serving-platform.adoc, modules/enabling-trustyai-service-using-cli.adoc, modules/enabling-trustyai-service-using-dashboard.adoc, modules/viewing-a-deployed-model.adoc
Adding links/references to Monitoring data science models modules
=> RHOAIENG-765 add references to bias monitoring

modules/configuring-your-ide.adoc
Actioning QE feedback from https://github.com/opendatahub-io/opendatahub-documentation/pull/150.
=> Incorporating QE feedback.

assemblies/working-with-distributed-workloads.adoc, modules/configuring-distributed-workloads.adoc, modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, modules/running-distributed-data-science-workloads-from-notebooks.adoc, working-on-data-science-projects.adoc
First set of updates, more to come
=> ENG-1729: Updates to distinguish upstream and downstream content for DW

modules/deploying-a-model-using-the-multi-model-serving-platform.adoc
Addressing review comments for RHOAIENG-666
Local Build
#Preview
=> RHOAIENG-666:Addressing review comments

modules/accessing-api-endpoints-for-models-deployed-on-single-model-server.adoc
Address QE feedback in RHOAIENG-1278.
=> Address QE feedback

modules/creating-a-bias-metric-using-cli.adoc, modules/creating-a-bias-metric-using-dashboard.adoc, modules/deleting-a-bias-metric-using-cli.adoc
**Creating a bias metric by using the CLI, Deleting a bias metric by using the CLI**
- Added prereq: You have a user token for authentication and you have passed the token to the TrustyAI service
- Added `-H "Authorization: Bearer $TOKEN"`  to all curl commands
**Creating a bias metric by using the dashboard**
- Added `-H "Authorization: Bearer $TOKEN" ` to all curl commands
- Updated step 2 to select project on the page
=> RHOAIENG-779 TrustyAI token

modules/authenticating-trustyai-service.adoc, modules/creating-a-bias-metric-using-cli.adoc, modules/creating-a-bias-metric-using-dashboard.adoc, modules/deleting-a-bias-metric-using-cli.adoc, modules/duplicating-a-bias-metric.adoc, modules/enabling-trustyai-service-using-cli.adoc, modules/enabling-trustyai-service-using-dashboard.adoc, modules/sending-training-data-to-a-model.adoc, modules/sending-training-data-to-models.adoc, monitoring-data-science-models.adoc
New sections for "Monitoring data science models" to address oauth changes and sending data to models
=> RHOAIENG-2668 TrustyAI oauth and sending data

modules/creating-a-bias-metric-using-cli.adoc, modules/creating-a-bias-metric-using-dashboard.adoc, modules/deleting-a-bias-metric-using-cli.adoc, modules/duplicating-a-bias-metric.adoc, modules/sending-training-data-to-a-model.adoc, modules/viewing-bias-metrics.adoc
=> RHOAIENG-2668_rev2

modules/creating-a-bias-metric-using-cli.adoc
Removes OS prompt, and changes http to https
=> ENG-2783: Fixes typos

modules/accessing-the-jupyter-administration-interface.adoc, modules/enabling-trustyai-service-using-dashboard.adoc, modules/overview-of-user-types-and-permissions.adoc, modules/stopping-notebook-servers-owned-by-other-users.adoc
=> cs link fixes

modules/creating-a-bias-metric-using-cli.adoc, modules/creating-a-bias-metric-using-dashboard.adoc, modules/sending-training-data-to-a-model.adoc
Applying typo fix for RHOIENG-2783 to another module an updating "sending data" verification steps from QE feedback
=> minor updates, 2783

modules/creating-a-bias-metric-using-dashboard.adoc, modules/deleting-a-bias-metric-using-dashboard.adoc, modules/duplicating-a-bias-metric.adoc, modules/enabling-trustyai-service-using-dashboard.adoc, modules/viewing-bias-metrics.adoc
Updating UI labels after accessing environment
=> TrustyAI UI updates

modules/configuring-a-pipeline-server.adoc
=> odh-2081 updates to configuring a pipeline server

modules/configuring-your-ide.adoc, modules/notebook-images-for-data-scientists.adoc, modules/options-for-notebook-server-environments.adoc
Adds tech preview notes for downstream code-server references.
Tested in npm preview.
=> RHOAIENG-2938 - Adds tech preview notes for downstream code-server references.

modules/options-for-notebook-server-environments.adoc
Adds a generic 'Technology Preview' note to modules/options-for-notebook-server-environments.adoc (limited to downstream).
=> Rhoaieng 2938 peer review updates

modules/accessing-notebook-servers-owned-by-other-users.adoc, modules/accessing-the-jupyter-administration-interface.adoc, modules/cleaning-up-after-deleting-users.adoc, modules/enabling-trustyai-service-using-cli.adoc, modules/enabling-trustyai-service-using-dashboard.adoc, modules/starting-notebook-servers-owned-by-other-users.adoc, modules/stopping-notebook-servers-owned-by-other-users.adoc
Updating links for new install TOC structure
=> RHOAIENG-3145 link updates for TOC restructure

modules/about-deleting-users-and-resources.adoc, modules/adding-users-to-specialized-data-science-user-groups.adoc, modules/authenticating-trustyai-service.adoc, modules/cleaning-up-after-deleting-users.adoc, modules/configuring-a-recommended-accelerator-for-notebook-images.adoc, modules/configuring-distributed-workloads.adoc, modules/enabling-habana-gaudi-devices.adoc, modules/enabling-trustyai-service-using-dashboard.adoc, modules/restoring-the-default-pvc-size-for-your-cluster.adoc, modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, modules/sending-training-data-to-a-model.adoc, modules/stopping-idle-notebooks.adoc
A few modules were missing the conditional changes, links, and updates to OSD references implemented as a part of RHOAIENG-1066/RHOAIENG-2670. This PR addresses and adds the updates to the remaining modules.
Local Build
=> RHOAIENG-2670:Updating remaining conditionals,links and OSD references

modules/viewing-metrics-for-the-single-model-serving-platform.adoc
Minor change to update conditional
Local Build
=> RHOAIENG-2828: Updating conditional

assemblies/serving-large-models.adoc, modules/accessing-inference-endpoints-for-models-deployed-on-single-model-server.adoc
RHOAIENG-3379
- Renaming section (and file name)
- Adding additional resources
Local Build
=> RHOAIENG-3379: Rename section and add additional resources

modules/accessing-inference-endpoints-for-models-deployed-on-single-model-server.adoc
fixing additional resources heading
local build
=> RHOAIENG-3379: Fixing additional resources heading

modules/configuring-your-ide.adoc, modules/notebook-images-for-data-scientists.adoc, modules/options-for-notebook-server-environments.adoc
Corrects links in rstudio disclaimers downstream.
=> Correcting links.

modules/configuring-your-ide.adoc, modules/notebook-images-for-data-scientists.adoc, modules/options-for-notebook-server-environments.adoc
Updating RStudio note links with the full URL.
=> Updating RStudio links.

modules/updating-the-deployment-properties-of-a-deployed-model.adoc, modules/viewing-http-request-metrics-for-a-deployed-model.adoc
https://issues.redhat.com/browse/RHOAIENG-3764
The Model Serving tab in the left menu of the dashboard now displays a page titled **Deployed Models**. Previously, this was the **Model Serving** page. This PR includes updates that reflect this change.
local build
=> RHOAIENG-3764: Updating page title

_artifacts/document-attributes-global.adoc, assemblies/upgrading-odh-v2.adoc, assemblies/working-with-certificates.adoc, installing-open-data-hub.adoc, modules/adding-a-ca-bundle-after-upgrading.adoc, modules/adding-a-ca-bundle.adoc, modules/managing-certificates.adoc, modules/removing-a-ca-bundle-from-a-namespace.adoc, modules/removing-a-ca-bundle.adoc, modules/understanding-certificates.adoc, upgrading-open-data-hub.adoc
New assembly for using self-signed certificates
=> RHOAIENG-2429 Certificates

assemblies/working-with-certificates.adoc, modules/adding-a-ca-bundle-after-upgrading.adoc, modules/adding-a-ca-bundle.adoc, modules/removing-a-ca-bundle-from-a-namespace.adoc, modules/removing-a-ca-bundle.adoc
=> RHOAIENG-2429 removing xrefs

modules/configuring-distributed-workloads.adoc
Adds prereq about self-signed certs to DW doc. Link to be added later
=> ENG-4473: Adds prereq about self-signed certs to DW doc

modules/adding-a-ca-bundle-after-upgrading.adoc, modules/adding-a-ca-bundle.adoc
Adding links to/from install/upgrade modules
=> Self-signed certs - adding links

modules/hiding-the-default-jupyter-application.adoc
Reverts opendatahub-io/opendatahub-documentation#227
=> Revert "odh-766-3-19 qe review comment"

modules/deploying-models-using-the-single-model-serving-platform.adoc
Remove alternative of disabling SSL entirely.
=> DS-4618_rev1 Revise note about using self-signed certs with KServe

modules/configuring-a-pipeline-server.adoc
Removing the note added for connecting to an unsecured database. This will moved to a knowledge base instead.
Local Build
=> RHOAIENG-4279: Removing note

modules/adding-an-application-to-the-dashboard.adoc
Fixing broken link
local build
=> RHOAIENG-4214: Fixing broken link

modules/preventing-users-from-adding-applications-to-the-dashboard.adoc
Fixing broken link for CS
Local Build
=> RHOAIENG-4214: Fixing broken link for CS

modules/using-certificates-with-data-science-pipelines.adoc
Updates references to 'pipelines-definition' metadata name.
=> Updating pipelines-definition references.

modules/viewing-performance-metrics-for-model-server.adoc
=> RHOAIENG-4564: Fixing xref

modules/about-model-serving.adoc, modules/about-the-single-model-serving-platform.adoc, modules/accessing-inference-endpoints-for-models-deployed-on-single-model-server.adoc, modules/deploying-models-on-the-single-model-serving-platform.adoc, modules/enabling-trustyai-service-using-cli.adoc, modules/enabling-trustyai-service-using-dashboard.adoc, modules/viewing-metrics-for-the-single-model-serving-platform.adoc, monitoring-data-science-models.adoc
Updating _single model_ to _single-model_.
Local build
=> RHOAIENG-4225: Updating single model to single-model

modules/overview-of-accelerators.adoc
Removes a duplicate list item.
=> Removing dupe list item (Overview of accelerators)

modules/accessing-authorization-token-for-model-deployed-on-single-model-serving-platform.adoc, modules/accessing-inference-endpoint-for-model-deployed-on-single-model-serving-platform.adoc, modules/deploying-models-on-the-single-model-serving-platform.adoc, modules/making-inference-requests-to-models-deployed-on-single-model-server.adoc
**Description**
- Initial merge to facilitate a **downstream** SME and peer review of the model serving guide
- Any required content changes post-review will be made via a `rev1` PR
=> DS-3011 Add upstream modules for authorization

assemblies/working-on-data-science-projects.adoc, modules/adding-a-data-connection-to-your-data-science-project.adoc, modules/adding-a-model-server-for-the-multi-model-serving-platform.adoc, modules/adding-cluster-storage-to-your-data-science-project.adoc, modules/configuring-a-pipeline-server.adoc, modules/configuring-your-ide.adoc, modules/creating-a-data-science-project.adoc, modules/creating-a-project-workbench.adoc, modules/deleting-a-data-connection.adoc, modules/deleting-a-data-science-project.adoc, modules/deleting-a-model-server.adoc, modules/deleting-a-workbench-from-a-data-science-project.adoc, modules/deleting-cluster-storage-from-a-data-science-project.adoc, modules/deploying-a-model-using-the-multi-model-serving-platform.adoc, modules/deploying-models-on-the-single-model-serving-platform.adoc, modules/enabling-trustyai-service-using-dashboard.adoc, modules/removing-access-to-a-data-science-project.adoc, modules/sharing-access-to-a-data-science-project.adoc, modules/starting-a-workbench.adoc, modules/the-open-data-hub-user-interface.adoc, modules/updating-a-connected-data-source.adoc, modules/updating-a-data-science-project.adoc, modules/updating-a-model-server.adoc, modules/updating-a-project-workbench.adoc, modules/updating-access-to-a-data-science-project.adoc, modules/updating-cluster-storage.adoc, modules/viewing-performance-metrics-for-model-server.adoc
Updates the doc based on new design for ds project details. 
Commits grouped as follows:
=> Eng 3998: Updates doc based on new design for ds project details

modules/deploying-models-on-the-single-model-serving-platform.adoc
**Description**
- Merge updates to facilitate a **downstream** SME, QE, and peer review of the model serving guide
- Any required content changes post-review will be made via a new PR
=> DS-3011_rev1 Update model deployment procedure

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc
Updates for Data Science Pipelines 2:
- Removed DSP Operator prereq
- New code example
=> ENG-3961: Updates for DSP2

modules/options-for-notebook-server-environments.adoc
Updates the Codeflare-SDK package version to 0.16 for the 2024.1 workbench images.
=> Updating the Codeflare SDK version for 2024.1 images.

modules/options-for-notebook-server-environments.adoc
Updates the Kfp package version to 2.5 for the 2024.1 Tensorflow workbench image.
=> Updates Kfp version for Tensorflow 2024.1 wbench image.

assemblies/working-with-data-science-pipelines.adoc, modules/enabling-data-science-pipelines-2.adoc
Adding some conditions for downstream notes.
=> DSP 2.0: Adding conditions.

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc
ENG-2278: Adds namespace support; ENG-5345: Adds callout for mTLS
=> ENG-2278+ENG-5345: Updates DW+DSP2 re namespace support and mTLS callout

assemblies/working-with-distributed-workloads.adoc, modules/monitoring-distributed-workloads.adoc, modules/running-distributed-workloads.adoc, modules/viewing-distributed-workload-status.adoc, modules/viewing-project-metrics-for-distributed-workloads.adoc, modules/viewing-the-status-of-distributed-workloads.adoc
=> ENG-5453: Adds docs for distributed workloads metrics

modules/configuring-distributed-workloads.adoc, modules/configuring-quota-management-for-distributed-workloads.adoc, modules/installing-odh-components.adoc, modules/overview-of-distributed-workloads.adoc, modules/running-distributed-data-science-workloads-from-notebooks.adoc
=> ENG-5153: Updates to add Kueue

modules/enabling-data-science-pipelines-2.adoc
=> Removing line on Argo CRDs.

modules/configuring-the-codeflare-operator.adoc
ENG-319: Adds new file to configure CodeFlare Operator
=> ENG-319: Adds new file to configure CodeFlare Operator

modules/configuring-distributed-workloads.adoc, modules/configuring-the-codeflare-operator.adoc
ENG-319: Fixes formatting and adds peer review feedback
=> ENG-319: Fixes formatting and adds peer review feedback

assemblies/working-with-data-science-pipelines.adoc, modules/configuring-the-distributed-workloads-components.adoc, modules/running-distributed-data-science-workloads-disconnected-env.adoc, modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, modules/running-distributed-data-science-workloads-from-notebooks.adoc
=> ENG-5142: Fixes broken links

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc
=> ENG-5142: Fixes ODH link

modules/viewing-metrics-for-the-single-model-serving-platform.adoc
Small change to update a section name
https://issues.redhat.com/browse/RHOAIENG-4984
Local build
=> RHOAIENG-4984: Updating section name

modules/importing-a-data-science-pipeline.adoc, modules/uploading-a-pipeline-version.adoc
Changed "Upload from file" to "Upload a file"
=> RHOAIENG-6665 upload a file

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc
ENG-6697: Fixes formatting problem in callout
=> ENG-6697: Fixes formatting problem in callout

modules/configuring-quota-management-for-distributed-workloads.adoc, modules/configuring-the-codeflare-operator.adoc, modules/running-distributed-data-science-workloads-disconnected-env.adoc, modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, modules/running-distributed-data-science-workloads-from-notebooks.adoc
=> ENG-6697: Fixes new links

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc
ENG-6697: Fixes <path> in callout2
=> ENG-6697: Fixes <path> in callout2

_artifacts/document-attributes-global.adoc, modules/about-the-single-model-serving-platform.adoc
- Added attribute for OpenShift Serverless docs latest version
- Updated OpenShift Serverless URLs with attribute
local build
=> RHOAIENG-6788: Updating serverless urls

modules/tutorials-for-data-scientists.adoc
Changed the brand name of Watson Studio  to include the IBM name.
=> DS-123456 test change to change Watson Studio name

modules/enabling-data-science-pipelines-2.adoc, modules/options-for-notebook-server-environments.adoc
Adding that notebook image versions must be manually updated to 2024.1 for DSP 2.0
=> DSP 2.0 notebook image versions

modules/overview-of-distributed-workloads.adoc
ENG-7533: Adds note to CodeFlare SDK paragraph
=> ENG-7533: Adds note to CodeFlare SDK paragraph

assemblies/collaborating-on-notebooks-using-git.adoc, assemblies/creating-and-importing-notebooks.adoc, assemblies/using-the-jupyter-application.adoc, working-on-data-science-projects.adoc, working-with-connected-applications.adoc
updates based on downstream fetch and test, plus for addressing any review comments
=> odh-7074-2 

assemblies/working-in-your-data-science-ide.adoc, modules/working-in-code-server.adoc
minor updates to address peer review comments found downstream
=> odh-7075-6-4 peer review comments

modules/enabling-gpu-support-in-data-science.adoc, working-on-data-science-projects.adoc, working-with-accelerators.adoc
Pulls the content from Working on data science projects > Working with accelerators into its own guide.
=> 521 Separate accelerator guide

modules/next-steps-getting-started.adoc, working-with-connected-applications.adoc
=> odh-8239-3 minor review comments

modules/running-distributed-data-science-workloads-disconnected-env.adoc
Adds info about certGeneratorImage
=> ENG-7651: Adds info about certGeneratorImage

assemblies/working-with-data-science-pipelines.adoc, modules/storing-data-with-data-science-pipelines.adoc
Module written on how pipeline data is stored when running a pipeline in RHOAI. The location of the storage depends on where you ran the pipeline from. For example, running a pipeline from the dashboard results in a different directory structure than running a pipeline from Elyra.
=> ENG-7700: Improve storage documentation when working with data science pipelines 

modules/running-distributed-data-science-workloads-disconnected-env.adoc, modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, modules/running-distributed-data-science-workloads-from-notebooks.adoc
ENG-7653: Adds info about required user roles to run distributed workloads
=> ENG-7653: Adds info about required user roles

modules/configuring-the-distributed-workloads-components.adoc
Removed one prerequisite from this section, as it is not needed here.
=> Removed 1 prerequisite from module

modules/accessing-inference-endpoint-for-model-deployed-on-single-model-serving-platform.adoc
Updated the steps to access inference endpoint information through Model Serving tab on the dashboard
Ran a local build in Gatbsy and confirmed that the changed text appeared in the relevant sections
=> Change UI workflow for accessing inference endpoint

modules/running-distributed-data-science-workloads-from-notebooks.adoc
ENG-7654: (DW) Adds info about labels dictionary, and reformats the substeps as numbered steps.
=> ENG-7654: (DW) Adds info about labels dictionary

modules/overview-of-kueue-resources.adoc, working-with-distributed-workloads.adoc
ENG-7656: Adds overview of Kueue resources
=> ENG-7656: Adds overview of Kueue resources

modules/starting-a-jupyter-notebook-server.adoc
ENG-4269: Updates based on new Home page
=> ENG-4269: Updates based on new Home page

modules/creating-a-project-workbench.adoc, modules/enabling-applications-connected.adoc
addressing QE comment for prereq of creating a workbench (7075)
=> odh-7074-b and 7075   - qe comments

modules/configuring-quota-management-for-distributed-workloads.adoc
ENG-8823: Adds note to clarify that all resources must have quota specified even if value is 0
=> ENG-8823: Adds note to specify quota for all resources even if zero

modules/configuring-quota-management-for-distributed-workloads.adoc
ENG-8823: Fixes formatting to correct substep numbering
=> ENG-8823: Fixes formatting

modules/configuring-quota-management-for-distributed-workloads.adoc, modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, modules/running-distributed-data-science-workloads-from-notebooks.adoc
ENG-7635: Removes more broken links
=> ENG-7635: Removes more broken links

modules/about-workbench-images.adoc, modules/accessing-notebook-servers-owned-by-other-users.adoc, modules/configuring-quota-management-for-distributed-workloads.adoc, modules/disabling-applications-connected.adoc, modules/enabling-gpu-support-in-data-science.adoc, modules/next-steps-getting-started.adoc, modules/removing-disabled-applications.adoc, modules/running-distributed-data-science-workloads-disconnected-env.adoc, modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, modules/running-distributed-data-science-workloads-from-notebooks.adoc, modules/starting-notebook-servers-owned-by-other-users.adoc, modules/stopping-notebook-servers-owned-by-other-users.adoc, modules/working-in-rstudio-server.adoc
ENG-9000: Fixes broken links in DW and other doc
=> ENG-9000: Fixes broken links

modules/next-steps-getting-started.adoc, modules/removing-disabled-applications.adoc
ENG-9000: Fixes more broken links
=> ENG-9000: Fixes more broken links

modules/starting-notebook-servers-owned-by-other-users.adoc, modules/stopping-notebook-servers-owned-by-other-users.adoc
ENG-9000: Fixes third group of broken links
=> ENG-9000: Fixes third group of broken links

assemblies/working-in-your-data-science-ide.adoc, modules/about-workbench-images.adoc
Removes if:cloud statements for the RStudio content.
=> Removing cloud limits for RStudio content.

assemblies/working-in-your-data-science-ide.adoc, modules/about-workbench-images.adoc
ENG-9000: Fixes broken links in cloud doc, and removes condition for RStudio
=> ENG-9000: Fixes broken links in cloud doc

modules/working-in-rstudio-server.adoc
ENG-9000: Fixes more broken links in cloud doc
=> ENG-9000: Fixes more broken links in cloud doc

modules/about-workbench-images.adoc
Updates two downstream links to the manual RStudio build steps.
=>  Updating links related to RStudio content move.

modules/about-workbench-images.adoc
=> Updating links.

modules/about-workbench-images.adoc
Actions feedback changes requested in downstream MR:
- Updates some phrasing to align with style guide.
=> 9163: PR feedback changes.

modules/about-workbench-images.adoc
Actioning downstream MR feedback and correcting a typo.
=> 9163: Corrections and feedback update

assemblies/managing-cluster-resources.adoc, modules/about-workbench-images.adoc, modules/enabling-intel-gaudi-ai-accelerators.adoc, modules/intel-gaudi-ai-accelerator-integration.adoc, modules/next-steps-getting-started.adoc, modules/overview-of-accelerators.adoc, modules/starting-a-jupyter-notebook-server.adoc, working-with-accelerators.adoc
Updates references to Habana Gaudi devices to Intel Gaudi AI Acclerators.
=> 9177: Intel accelerator naming updates

_artifacts/document-attributes-global.adoc, assemblies/managing-data-science-pipelines.adoc, assemblies/managing-pipeline-runs.adoc, assemblies/working-with-pipeline-logs.adoc, assemblies/working-with-pipelines-in-jupyterlab.adoc, modules/adding-notebook-pod-tolerations.adoc, modules/defining-a-pipeline.adoc, modules/deleting-a-data-science-pipeline.adoc, modules/enabling-data-science-pipelines-2.adoc, modules/next-steps-getting-started.adoc, modules/requirements-for-upgrading-odh.adoc, modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, working-on-data-science-projects.adoc, working-with-data-science-pipelines.adoc
Moving the pipelines chapter out of the Working on data science projects into a new guide/book
=> odh-8308 create pipelines guide

assemblies/configuring-the-odh-operator-logger.adoc, assemblies/upgrading-odh-v2.adoc, modules/logging-in.adoc, working-on-data-science-projects.adoc
=> Odh 9173 2

_artifacts/document-attributes-global.adoc, modules/cleaning-up-after-deleting-users.adoc, modules/overview-of-user-types-and-permissions.adoc
Update to remove or replace instances of the RHODS acronym which can be removed/replaced.
=> Update to remove or replace instances of the RHODS acronym 

modules/enabling-data-science-pipelines-2.adoc
Fixes the formatting of a note in Enabling DSP 2.0.
=> Fixes note formatting.

modules/troubleshooting-common-problems-with-distributed-workloads-for-administrators.adoc, modules/troubleshooting-common-problems-with-distributed-workloads-for-users.adoc
ENG-7652: Follow-up to address SME feedback:
Removes the entry for a known issue already documented in the release notes, and adds extra steps in other items
=> ENG-7652: Follow-up to address SME feedback

modules/overview-of-accelerators.adoc
Removes a now-incorrect reference to HPUs.
=> Remove HPU ref.

modules/enabling-trustyai-service-using-dashboard.adoc
Fix broken link discovered in post-release link checking activity
Corrected link and tested it in preview environment
=> Fix broken link

modules/running-distributed-data-science-workloads-disconnected-env.adoc
=> odh-fix-link-211

assemblies/installing-odh-v2.adoc, assemblies/monitoring-distributed-workloads.adoc, assemblies/upgrading-odh-v2.adoc, modules/configuring-a-pipeline-server.adoc, modules/creating-a-runtime-configuration.adoc, modules/enabling-data-science-pipelines-2.adoc, modules/overview-of-distributed-workloads.adoc, modules/overview-of-pipelines-in-jupyterlab.adoc, modules/updating-a-runtime-configuration.adoc, working-with-data-science-pipelines.adoc
Corrects unapproved short form references to pipelines. 
Does not affect capitalisation of UI elements, code examples, or specific custom resource names.
=> 9932: Correcting short form references to pipelines.

assemblies/running-distributed-workloads.adoc
Updating conditional within assembly to restrict module to self-managed-->
Local build
=> RHOAIENG-7395: Fixing conditional in assembly

assemblies/installing-odh-v2.adoc, assemblies/upgrading-odh-v2.adoc, modules/configuring-a-pipeline-server.adoc, modules/enabling-data-science-pipelines-2.adoc, working-with-data-science-pipelines.adoc
Updates references to the 2.9 RHOAI version
=> Updating 2.9 version refs.

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc
Reverts opendatahub-io/opendatahub-documentation#382
=> Revert "Remove prerequisite about logging in as a cluster admin"

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc
Reverts opendatahub-io/opendatahub-documentation#383
=> Revert "Revert "Remove prerequisite about logging in as a cluster admin""

modules/configuring-access-to-a-data-science-project.adoc, modules/sharing-access-to-a-data-science-project.adoc, modules/updating-access-to-a-data-science-project.adoc
small PR - update three files that mentioned the *Edit* permission for projects, change Edit to Contributor
=> odh-9999 change UI label from Edit to Contributor

working-on-data-science-projects.adoc
Removes a note from the _Working on data science projects_ title. The note is not applicable from the upcoming version.
=> 10544: Removing project note.

modules/deploying-models-on-the-single-model-serving-platform.adoc
Updated documentation to cover new UI option to make endpoints public for the single model serving platform
Made updates and verified that they appear as expected in a stage environment
=> Document ability to make endpoints public or private

modules/configuring-the-distributed-workloads-components.adoc, modules/enabling-nvidia-gpus.adoc
ENG-9936: Updates to clarify GPU support limitation
=> ENG-9936: Updates to clarify GPU support limitation

assemblies/configuring-distributed-workloads.adoc
ENG-11060: Uncomments missing module
=> ENG-11060: Uncomments missing module

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc
ENG-10138: Updates to replace deprecated num_gpus parameter  (CodeFlare SDK)
=> ENG-10138: Updates to replace deprecated num_gpus parameter

modules/enabling-nvidia-gpus.adoc
ENG-9936: Adds condition to note to exclude it upstream
=> ENG-9936: Adds condition to note to exclude it upstream

assemblies/customizing-component-deployment-resources.adoc, modules/customizing-component-resources.adoc, modules/disabling-component-resource-customization.adoc
Updating contexts for the custom component resources content.
=> Correcting contexts.

modules/duplicating-a-bias-metric.adoc, modules/installing-trustyai-service-using-cli.adoc, modules/installing-trustyai-service-using-dashboard.adoc
Removing xrefs so previews work downstream
=> removing xrefs

assemblies/configuring-trustyai.adoc, modules/configuring-trustyai-with-a-database.adoc, modules/enabling-trustyai-component.adoc, modules/installing-trustyai-service-using-cli.adoc, modules/installing-trustyai-service-using-dashboard.adoc
New module for configuring TrustyAI with a database
=> RHOAI-11088 TrustyAI database

modules/configuring-trustyai-with-a-database.adoc, modules/enabling-trustyai-component.adoc
=> removing xrefs for upstream preview

modules/optimizing-the-vllm-runtime.adoc
Addressing additional downstream feedback upstream
Local build
=> RHOAIENG-10023: Addressing review feedback

modules/viewing-performance-metrics-for-deployed-model.adoc
Elaborating UWM prereq for kserve perf metrics
Local build
=> RHOAIENG-4198: Elaborating UWM prereq for kserve perf metrics

modules/configuring-trustyai-with-a-database.adoc, modules/disabling-component-resource-customization.adoc, modules/optimizing-the-vllm-runtime.adoc, modules/viewing-http-request-metrics-for-a-deployed-model.adoc, modules/viewing-performance-metrics-for-deployed-model.adoc
Fixes some links that appeared in a pre-publishing link check.
=> Pre publish link fix

modules/optimizing-the-vllm-runtime.adoc
Removing a step from a procedure as per SME feedback
Local Build
=> RHOAIENG-10023: removing step 7 as per SME feedback

modules/creating-a-project-workbench.adoc
Corrects a link to a section that had a downstream title change.
=> Correcting downstream s3 link.

modules/optimizing-the-vllm-runtime.adoc
Adding note to address RHOAIENG-11084
Local Build
=> RHOAIENG-10023: Adding note to address RHOAIENG-11084

modules/customizing-component-resources.adoc
update 1x link for 2.12 to fetch downstream.
=> update 1x link for 2.12 to fetch downstream

modules/a-new-file-test.adoc
=> new file for fetch script test

modules/a-new-file-test2.adoc
=> fetch script test

modules/adding-a-custom-model-serving-runtime-for-the-multi-model-serving-platform.adoc, modules/adding-a-custom-model-serving-runtime-for-the-single-model-serving-platform.adoc
Rework note about custom runtime support
Created local build and confirmed changes appeared in preview
=> Rework custom runtime support note for clarity

assemblies/working-with-data-in-s3-compatible-object-store.adoc, modules/copying-files-between-buckets.adoc, modules/creating-a-bucket.adoc, modules/creating-an-s3-client.adoc, modules/deleting-a-bucket.adoc, modules/deleting-files-in-bucket.adoc, modules/downloading-files-from-bucket.adoc, modules/listing-available-buckets.adoc, modules/listing-files-in-bucket.adoc, modules/s3-prerequisites.adoc, modules/uploading-files-to-bucket.adoc, working-with-data-in-s3-compatible-object-store.adoc
Adding the S3 guide upstream
Local Build
=> RHOAIENG-11856: Adding S3 guide upstream

working-with-data-science-pipelines.adoc
Slightly rewords a line in the working-with-data-science-pipelines.adoc assembly for accuracy, formats some top-level list items in bold for scannability.
=> Minor pipelines reword and format

_artifacts/document-attributes-global.adoc
Added attributes for the long and shortened form of Red Hat Enterprise Linux AI.
=> Add attributes for RHELAI

modules/deploying-models-on-the-single-model-serving-platform.adoc
Added information about requirements for deploying RHEL AI models
Built changes locally and confirmed that changes appeared as expected.
=> Add information about how to deploy RHEL AI models

modules/deploying-models-on-the-single-model-serving-platform.adoc
Fix formatting of note 
Built locally and confirmed note appeared as expected
=> Fix note formatting

modules/using-certificates-with-workbenches.adoc
Adds a missing bracket to a note in Using certificates with workbenches.
=> Adding missing bracket

modules/adding-a-model-server-for-the-multi-model-serving-platform.adoc, modules/deploying-models-on-single-node-openshift-using-kserve-raw-deployment-mode.adoc, modules/deploying-models-on-the-single-model-serving-platform.adoc
Clarifies 3 prereqs by adding 'NVIDIA'.
=> 776: Updating references to 'GPU Operators'.

modules/overview-of-kueue-resources.adoc
ENG-12318: Removes conflicting info about supported Kueue resources
=> ENG-12318: Removes conflicting info about supported Kueue resources

modules/configuring-the-training-job.adoc
ENG-11440: Updates with additional QE feedback
=> ENG-11440: Updates with QE feedback

modules/s3-prerequisites.adoc
Fixing links in S3 prereq section
Local build
=> RHOAIENG-12854: Fixing links in S3 prereq section

modules/updating-the-deployment-properties-of-a-deployed-model.adoc
Updated labels in the documentation to reflect updates made to UI elements.
Built documentation locally and confirmed changes appear as expected
=> Update UI labels to reflect recent changes

assemblies/serving-large-models.adoc, modules/deploying-models-on-the-single-model-serving-platform.adoc, modules/ref-inference-endpoints.adoc
Moved sample commands to be closer to endpoints
Also fixed minor note formatting issue
Made changes, built locally, and verified that changes appeared as expected
=> Combine sample commands with endpoints in reference topic

assemblies/managing-cluster-pvc-size.adoc, assemblies/managing-notebook-servers.adoc, managing-resources.adoc
moving modules and assemblies to new cluster admin guide
=> rhoai-9865 managing users update

modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, modules/running-distributed-data-science-workloads-from-notebooks.adoc
ENG-12819: Updates the Ray cluster image references
=> ENG-12819: Updates the Ray cluster image references

modules/adding-a-tested-and-verified-runtime-for-the-multi-model-serving-platform.adoc, modules/adding-a-tested-and-verified-runtime-for-the-single-model-serving-platform.adoc, modules/ref-inference-endpoints.adoc
Addressing SME feedback
Local Build
=> RHOAIENG-8167: Addressing SME feedback

modules/adding-cluster-storage-to-your-data-science-project.adoc, modules/creating-a-project-workbench.adoc, modules/creating-a-workbench-select-ide.adoc, modules/updating-cluster-storage.adoc
Adding reference to new "storage class" field. 
Reformatting "Creating a workbench" module to match other modules and newer UI.
=> New storage class field

modules/about-workbench-images.adoc
Update to table in RHOAI docs to reference a repo link
=> Update to table in RHOAI docs to reference a repo link

assemblies/serving-large-models.adoc, modules/ref-tested-verified-runtimes.adoc
Create reference topic detailing tested and verified runtimes
Built locally and confirmed changes appeared as expected
=> Create reference for tested and verified runtimes

modules/adding-an-application-to-the-dashboard.adoc, modules/viewing-http-request-metrics-for-a-deployed-model.adoc, modules/viewing-performance-metrics-for-deployed-model.adoc
=> odh-13031 fix links

modules/adding-a-tested-and-verified-runtime-for-the-single-model-serving-platform.adoc
Small change to remove an annotation
Local build
=> RHOAIENG-8167: Removing annotation as per SME feedback

assemblies/serving-large-models.adoc, modules/about-the-NVIDIA-NIM-model-serving-platform.adoc, modules/deploying-models-on-the-NVIDIA-NIM-model-serving-platform.adoc, modules/enabling-the-nvidia-nim-model-serving-platform.adoc
Adding initial NVIDIA NIM content:
- Intro module
- Enable NVIDIA NIM
- Deploy model with NVIDIA NIM
Local build
[Enabling_deploying_NVIDIA.pdf](https://github.com/user-attachments/files/17310155/Enabling_deploying_NVIDIA.pdf)
=> RHOAIENG-9795: Adding NVIDIA NIM

modules/deploying-models-on-the-NVIDIA-NIM-model-serving-platform.adoc
=> RHOAIENG-9795: small fix

modules/deploying-models-on-the-NVIDIA-NIM-model-serving-platform.adoc, modules/enabling-the-nvidia-nim-model-serving-platform.adoc
Addressing SME feedback
Local build
=> RHOAIENG-9795: Updates for NVIDIA NIM

modules/creating-a-custom-image-from-your-own-image.adoc
address QE comment for pip install command - add RUN
=> odh-769 address follow-up qe comments

assemblies/managing-custom-training-images.adoc, modules/about-base-images-for-distributed-workloads.adoc, modules/about-base-training-images.adoc
ENG-13752: Adds info about default dw base images
=> ENG-13752: Adds info about default base training images

modules/executing-a-pipeline-run.adoc
=> RHOAI-13466 add 255 character limit

modules/configuring-the-training-job.adoc
=> ENG-13645: Adds QLoRA info

assemblies/configuring-cluster-storage.adoc, assemblies/managing-storage-classes.adoc, managing-resources.adoc, modules/adding-cluster-storage-to-your-data-science-project.adoc, modules/changing-the-storage-class-for-an-existing-cluster-storage-instance.adoc, modules/configuring-storage-class-settings.adoc, modules/configuring-the-default-pvc-size-for-your-cluster.adoc, modules/configuring-the-default-storage-class-for-your-cluster.adoc, modules/creating-a-custom-image-from-your-own-image.adoc, modules/creating-a-project-workbench.adoc, modules/updating-cluster-storage.adoc
New assembly for Managing storage classes
New module for changing the storage class
=> RHOAI-11424 Storage classes

assemblies/managing-custom-training-images.adoc, modules/about-base-training-images.adoc, modules/about-workbench-images.adoc, modules/creating-a-custom-training-image.adoc, modules/pushing-an-image-to-the-integrated-openshift-image-registry.adoc, working-with-distributed-workloads.adoc
ENG-14128: Updates to add KFTO base image
=> ENG-14128: Updates to add KFTO base image

modules/editing-the-dashboard-configuration-file.adoc, modules/ref-dashboard-configuration-options.adoc
ENG-13968: Updates the dashboard configuration parameters; removes a YAML example
=> ENG-13968: Updates the dashboard configuration section

modules/configuring-the-model-registry-component.adoc, modules/creating-a-model-registry.adoc, modules/installing-odh-components.adoc
=> Link fixes to align with new naming.

modules/ref-dashboard-configuration-options.adoc
ENG-13968: Replaces 'authorization' with 'authentication'
=> ENG-13968: Replaces 'authorization' with 'authentication'

modules/accessing-your-workbench-ide.adoc, modules/adding-a-data-connection-to-your-data-science-project.adoc, modules/adding-cluster-storage-to-your-data-science-project.adoc, modules/configuring-storage-class-settings.adoc, modules/creating-a-data-science-project.adoc, modules/creating-a-project-workbench.adoc, modules/creating-an-s3-client.adoc, modules/starting-a-workbench.adoc, modules/updating-a-data-science-project.adoc, modules/updating-access-to-a-data-science-project.adoc, modules/updating-cluster-storage.adoc, modules/working-in-code-server.adoc
ENG-11303: Updates based on redesigned Projects page
=> ENG-11303: Updates based on redesigned Projects page

modules/configuring-the-model-registry-component.adoc, modules/overview-of-model-registries.adoc
- Adds some crosslinks to the model registry overview from downstream, to make the separate titles more visible regardless of which the user accesses.
- 
- Corrects a link label.
=>  Adding some crosslinks to the model registry overview.

modules/configuring-quota-management-for-distributed-workloads.adoc, modules/configuring-the-codeflare-operator.adoc
ENG-13155: Fixes broken links in inst guides
=> ENG-13155: Fixes broken links in inst guides

assemblies/configuring-cluster-storage.adoc, modules/updating-cluster-storage.adoc
Removing module until bugs fixed and steps can be verified.
=> Removing module

modules/about-base-training-images.adoc, modules/creating-a-custom-training-image.adoc, modules/enabling-the-nvidia-nim-model-serving-platform.adoc
=> upstream link fixes x3

modules/deploying-models-on-the-NVIDIA-NIM-model-serving-platform.adoc
=> updated link NVIDIA

assemblies/configuring-cluster-storage.adoc, modules/accessing-your-workbench-ide.adoc, modules/changing-the-storage-class-for-an-existing-cluster-storage-instance.adoc, modules/creating-an-s3-client.adoc, modules/updating-cluster-storage.adoc, modules/working-in-code-server.adoc
- Updated the procedure with the revised steps after a walk-through with dev
- Updated other modules to reflect Start/Stop being removed from the Action menu
=> Changing storage class procedure

modules/next-steps-getting-started.adoc
=> odh-9851 one word change

modules/overview-of-upgrading-odh.adoc, modules/requirements-for-upgrading-odh.adoc
Added note to add new components to DataScienceCluster object after upgrading
=> Note to add new component after upgrade

modules/ref-dashboard-configuration-options.adoc
ENG-14433: Changes 'disableBiasMetrics' to 'disableTrustyBiasMetrics'
=> ENG-14433: Changes 'disableBiasMetrics' to 'disableTrustyBiasMetrics'

assemblies/installing-odh-v2.adoc, installing-open-data-hub.adoc, modules/configuring-quota-management-for-distributed-workloads.adoc, modules/configuring-the-codeflare-operator.adoc
Reorg to be consistent with changes requested downstream
=> Reorg from downstream peer review

modules/deploying-models-on-the-single-model-serving-platform.adoc
- Added Authorino as a prereq for token authorization and model routes
- UI updates
Local build
=> RHOAIENG-15549: Adding Authorino prereq

modules/deploying-models-on-the-single-model-serving-platform.adoc
Addressing peer review feedback
Local build
=> RHOAIENG-15549: Addressing peer feedback

modules/archiving-a-model-version.adoc, modules/archiving-a-model.adoc, modules/creating-a-model-registry.adoc, modules/viewing-registered-model-versions.adoc, modules/viewing-registered-models.adoc
Minor updates to align with latest changes to the model registry UI.
- Adds info on the levels and values queried by the MR searches.
- Adds 'unique' qualifier and note to the *Name* step of creating a MR.
- Adds notes highlighting that models/versions with deployments cannot be archived.
- Corrects a downstream link in modules/viewing-registered-model-versions.adoc.
=> Minor updates to align with latest model reg UI

modules/creating-a-custom-training-image.adoc, modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, modules/running-distributed-data-science-workloads-from-notebooks.adoc
ENG-15220: Updates to document Python 3.11 Ray images
=> ENG-15220: Updates to document Python 3.11 Ray images

modules/overview-of-upgrading-odh.adoc
Adds a note on the ODH 2.19>2.20 upgrade issue to the Upgrading ODH title.
=> Adding MR known issue note to upgrades title.

modules/creating-a-model-registry.adoc, modules/overview-of-upgrading-odh.adoc
- Updates some of the steps in the model registry creation procedure.
- Removes a line from the MR upgrade issue note in _Upgrading ODH_
=> Updates MR creation steps

assemblies/managing-data-science-pipelines.adoc, modules/overview-of-data-science-pipelines-caching.adoc
This content explains how caching works when using data science pipelines, so that users can understand how to leverage caching for more efficient pipeline runs and how to disable caching when necessary.
Kubeflow Pipelines support caching to reduce redundant executions and enhance pipeline efficiency, as explained in the upstream document Kubeflow Pipelines - Caching. To help users make the most of this feature, we should enhance the existing "Working with data science pipelines" documentation to explain:
How caching works in RHOAI.
How cached pipeline steps are displayed in the UI.
How users can disable caching if needed.
=> ODH-9352 - initial draft of dsp caching docs

modules/adding-a-data-connection-to-your-data-science-project.adoc, modules/overview-of-data-science-pipelines-caching.adoc, modules/overview-of-object-storage-endpoints.adoc
=> minor typo fixes

modules/configuring-trustyai-with-a-database.adoc, modules/installing-trustyai-service-using-cli.adoc
Small update to further outline the database secret credentials and explain that this storage type is preferable over PVC.
=> db secret update for 2.15

modules/deploying-models-on-single-node-openshift-using-kserve-raw-deployment-mode.adoc
Change product names with improper capitalization to attributes.
=> Change product names to attributes

assemblies/creating-custom-workbench-images.adoc, modules/importing-a-custom-workbench-image.adoc
=> link fixes lines 8, 9

modules/creating-a-bias-metric-using-cli.adoc, modules/creating-a-bias-metric-using-dashboard.adoc, modules/deleting-a-bias-metric-using-cli.adoc, modules/viewing-bias-metrics.adoc
Fixes some broken links and adds missing conditions the following trustyai modules:
- Creating a bias metric by using the CLI
- Viewing bias metrics for a module
- Creating a bias metric by using the dashboard
=> Fix for some broken links in trustyai section

_artifacts/document-attributes-global.adoc, modules/adding-a-data-connection-to-your-data-science-project.adoc, modules/creating-a-bias-metric-using-cli.adoc, modules/creating-a-bias-metric-using-dashboard.adoc, modules/deleting-a-drift-metric-using-cli.adoc, modules/duplicating-a-bias-metric.adoc, modules/viewing-bias-metrics.adoc
Updated OCP attribute to 4.17 and fixed broken links
=> 2.15 link fix and OCP 4.17

assemblies/configuring-trustyai.adoc
=> removing note

assemblies/setting-up-trustyai-for-your-project.adoc, modules/installing-trustyai-service-using-cli.adoc, modules/installing-trustyai-service-using-dashboard.adoc, modules/t-bias-setting-up-your-environment.adoc
Removing more model-mesh only notes for TrustyAI, no longer applicable
=> Removing more notes

modules/configuring-trustyai-with-a-database.adoc, modules/overview-of-model-monitoring.adoc
=> updated according to peer review

modules/configuring-trustyai-with-a-database.adoc, modules/installing-trustyai-service-using-cli.adoc, modules/overview-of-model-monitoring.adoc
Updates in response to Neha and Adolfo QE checks for 2.15 to be pulled downstream (single sourcing)
=> Updates in response to Neha and Adolfo QE checks for 2.15

modules/troubleshooting-dspa-component-errors.adoc, working-with-data-science-pipelines.adoc
To improve support for users encountering issues with data science pipeline server (DSPA) setup in Red Hat OpenShift AI, we have provided a troubleshooting guide. This guide will focus on common errors displayed in DSPA conditions and offer  solutions for these issues. The documentation will help users self-diagnose and resolve problems related to pipeline server creation and configuration.
=> ODH-13650 - initial draft of DSP server config troubleshooting

managing-odh.adoc
ENG-15881: Includes example Kueue resource configs
=> ENG-15881: Includes example Kueue resource configs

lmeval-evaluation-job.adoc, lmeval-scenarios.adoc
Updates from Adolfo (QE) re text of lm eval modules
=> Updates from Adolfo (QE) re text

modules/enabling-the-nvidia-nim-model-serving-platform.adoc
Add note for users upgrading to TP 2.16
Local build
=> RHOAIENG-9796: Add note for users upgrading to TP 2.16

modules/managing-ray-clusters-from-within-a-jupyter-notebook.adoc
ENG-15181: Adds info about Refresh Data widget
=> ENG-15181: Adds info about Refresh Data widget

modules/optimizing-the-vllm-runtime.adoc
* Updated procedure to use config parameters
* Updated title
Local build
=> RHOAIENG-14033: Updating procedure 3.16.1 to use config parameters plus title update

modules/deploying-models-on-the-single-model-serving-platform.adoc, modules/ref-inference-endpoints.adoc, modules/ref-supported-runtimes.adoc
Adding vllm-gaudi runtime to serving docs and updating relevant sections
Local Build
=> RHOAIENG-16326: Adding vllm-gaudi runtime info

modules/enabling-the-nvidia-nim-model-serving-platform.adoc
=> RHOAIENG-9796: formatting fix

_artifacts/document-attributes-global.adoc
Updated OCP minimum attribute to 4.14 because 4.13 EOL was on Nov 17
=> Update OCP minimum to 4.14

assemblies/serving-large-models.adoc, modules/customizable-model-serving-runtime-parameters.adoc, modules/optimizing-the-vllm-runtime.adoc, modules/serving-runtime-parameters.adoc
Adds a small reference module containing links to the available resources on customizable runtime parameters.
+ Corrects an existing link in modules/optimizing-the-vllm-runtime.adoc.
=> ENG-11753: Reference docs for altering serving runtime parameters

modules/customizable-model-serving-runtime-parameters.adoc
Removes a duplicate 'link:' from link formatting.
=> Correcting typo in link format.

assemblies/serving-large-models.adoc, modules/deploying-models-using-multiple-gpu-nodes.adoc
Documentation describing how to deploy models on multiple GPU nodes for tech preview
Created local build and confirmed changes appeared as expected
=> Tech preview: Multinode, multi GPU deployment

assemblies/configuring-trustyai.adoc, modules/configuring-monitoring-for-your-model-serving-platform.adoc
updating trustyAI model serving platform configuration info
=> updating trustyAI model serving platform configuration info

modules/creating-a-data-science-project.adoc, modules/creating-a-project-workbench.adoc, working-in-your-data-science-ide.adoc
Minor suggestions from QE during RHOAI-10810 testing
=> Workbench updates from QE

modules/enabling-intel-gaudi-ai-accelerators.adoc, modules/intel-gaudi-ai-accelerator-integration.adoc
These are the updates required for the Gaudi 3 enablement in RHOAI.
=> ODH-16889 - updates for Gaudi 3 integration

modules/adding-a-connection-to-your-data-science-project.adoc, modules/deploying-models-using-multiple-gpu-nodes.adoc, modules/labeling-data-fields.adoc, modules/overview-of-model-registries.adoc
=> Misc link corrections.

assemblies/installing-odh-v2.adoc, assemblies/upgrading-odh-v1-to-v2.adoc, assemblies/upgrading-odh-v2.adoc, modules/defining-a-pipeline.adoc, modules/enabling-data-science-pipelines-2.adoc, modules/installing-the-odh-operator-v2.adoc, modules/requirements-for-upgrading-odh-v1.adoc, modules/requirements-for-upgrading-odh-v2.adoc, modules/using-certificates-with-data-science-pipelines.adoc, upgrading-open-data-hub.adoc, working-with-data-science-pipelines.adoc
=> DSP v1 removal

modules/adding-a-connection-to-your-data-science-project.adoc
Post release link checks - one to correct.
=> Corrects a link to object storage endpoints doc.

modules/adding-a-connection-to-your-data-science-project.adoc
Adds the {default-format-url} attribute to a link.
=> Corrects link format

modules/adding-a-connection-to-your-data-science-project.adoc, modules/managing-model-registry-permissions.adoc
Adds an underscore to the module id of modules/managing-model-registry-permissions.adoc
=> Correcting module ID context

modules/accessing-the-pipeline-editor.adoc
=> Accessing pipeline editor improvements

modules/installing-trustyai-service.adoc
RHOAIENG-16936  - update with note about non-OVMS models
=> RHOAIENG-16936 - add note

modules/accessing-s3-compatible-object-storage-with-self-signed-certificates.adoc
Splits 2 links onto separate lines to avoid downstream build issues.
=> Updating link location for S3/single cert content

modules/creating-a-connection-type.adoc, modules/deleting-a-connection-type.adoc, modules/duplicating-a-connection-type.adoc, modules/editing-a-connection-type.adoc
=> odh-17213-2 fixing links

modules/deploying-a-model-using-the-multi-model-serving-platform.adoc
RHOAI-17299 fix for missing serving model sections
=> Fix for missing serving model sections

modules/deploying-a-model-using-the-multi-model-serving-platform.adoc
Fixed formatting that broke presentation of steps
Built changes locally and confirmed they appeared as expected
=> Fix step formatting

modules/deploying-models-on-the-single-model-serving-platform.adoc, modules/ref-inference-endpoints.adoc, modules/ref-supported-runtimes.adoc
Adding vLLM ROCm runtime
Local build
=> RHOAIENG-16328:  Adding vLLM ROCm

modules/ref-supported-runtimes.adoc
Adding ROCm runtime to deployment requirements table
Local build
=> RHOAIENG-16328: Adding ROCm runtime to deployment requirements table

modules/ref-dashboard-configuration-options.adoc
ENG-17649: Updates the dashboard config options for 2.16
=> ENG-17649: Updates the dashboard config options for 2.16

modules/migrating-to-data-science-pipelines-2.adoc, modules/requirements-for-upgrading-odh-v2.adoc, working-with-data-science-pipelines.adoc
RHOAI-16973, renaming module to be more accurate and updating links.
=> Rename Enabling data science pipelines 2.0

_artifacts/document-attributes-global.adoc
Updates the upstream YEAR attribute value from '2024' to '2025'.
=> ENG-17144: Updates the YEAR attribute value for 2025

modules/setting-timeout-for-kserve.adoc
Remove adoc extension from module context
=> Remove adoc extension from topic

modules/overview-of-model-registries.adoc
Corrects the downstream conditioning in the model registry overview module.
=> ENG-18320: Corrects condition in MR overview

modules/ref-dashboard-configuration-options.adoc
ENG-17649: Conditionalises the disableTracking default value for ODH and RHOAI
=> ENG-17649: Conditionalises the disableTracking default value for ODH and RHOAI

modules/enabling-the-nvidia-nim-model-serving-platform.adoc
Updating NIM enablement instructions to include the following prereqs:
- Access to NCA account and NGC portal
- NGC API Key
Local build
=> RHOAIENG-18022: Updating NIM enablement instructions

modules/lmeval-evaluation-job.adoc
FIxing upstream formatting issue for downstream rendering
=> 12677_FIxing upstream formatting issue for downstream rendering

modules/deploying-model-stored-in-oci-image.adoc, modules/storing-a-model-in-oci-image.adoc
Backporting changes from upstream fetch
Created local build and confirmed changes appeared as expected.
=> Deploying OCI models fast follow patch

modules/about-the-NVIDIA-NIM-model-serving-platform.adoc, modules/deploying-models-on-the-NVIDIA-NIM-model-serving-platform.adoc, modules/enabling-the-nvidia-nim-model-serving-platform.adoc
- Removed tech preview notice
- Minor UI and instruction updates
- Added reference link to NVIDIA NIM API endpoints
[Serving models.pdf](https://github.com/user-attachments/files/18527289/Serving.models.pdf)
Local build
=> RHOAIENG-18466: NIM GA updates

modules/lmeval-evaluation-job.adoc
Update LMEval module to shorten or remove external URLs
=> ENG-12677_URLsRefactoring

modules/lmeval-scenarios.adoc, modules/setting-up-lmeval.adoc
minor updates to address peer review feedback
=> jira15677_Updates to LMEval single sourced docs 

modules/optimizing-the-vllm-runtime.adoc
Corrects an out of date link to https://docs.vllm.ai/en/latest/serving/engine_args.html.
=> Correcting a link to vLLM engine args

modules/deploying-model-stored-in-oci-image.adoc
Corrects a downstream link to _Storing a model in an OCI image_.
=> Correcting OCI image link.

modules/storing-a-model-in-oci-image.adoc
Adds a context underscore to the module ID.
=> OCI model storage: Adding context underscore to module ID

modules/deploying-model-stored-in-oci-image.adoc
Corrects a link in modules/deploying-model-stored-in-oci-image.adoc.
=> Correcting OCI model storage link.

modules/enabling-nvidia-gpus.adoc
…en enabling nvidia gpus
To make the "Enabling NVIDIA GPUs" module a little more consistent with the other accelerator modules, information on the Node Feature Discovery (NFD) and Kernel Module Management (KMD) have been added to the module in the "Verification" section. In addition, the "Prerequisite" section has been enhanced to include information that the GPU itself must be present in the deployment before the accelerator can be enabled.
=> ENG-17238 - Enhance "Enabling NVIDIA GPUs" with further information within the prereqs and verification section

modules/deploying-models-using-multiple-gpu-nodes.adoc
Add condition for prerequisite
=> Add condition for prerequisite

assemblies/serving-large-models.adoc, modules/enabling-metrics-for-existing-nim-deployment.adoc
Procedural module [Enabling NIM metrics for existing deployments]
Local build
PDF for downstream preview: [NIMmetrics.pdf](https://github.com/user-attachments/files/18677751/NIMmetrics.pdf)
=> RHOAIENG-18528: Procedural module [enabling NIM metrics for existing deployments]

modules/deploying-models-using-multiple-gpu-nodes.adoc
Added missing colon to fix broken conditions
=> Second revision broken conditions

modules/creating-a-model-registry.adoc, modules/editing-a-model-registry.adoc, working-with-model-registries.adoc
Updates the 'Creating a model registry' proc to include new UI options for using a CA cert with your DB connections.
Adds an 'Editing a model registry' proc.
=> ENG-17044: Model registry Create/Edit form updates

modules/creating-a-model-registry.adoc, modules/editing-a-model-registry.adoc
Corrects osd-latest-version attribute label in 2 modules.
=> ENG-17044: Correcting attribute label in MR docs.

modules/creating-a-model-registry.adoc, modules/registering-a-model.adoc
Updates a couple of instances of 'page' to 'dialog', to align with the UI.
=> MR content: Correcting 'page' to 'dialog'.

modules/about-model-serving.adoc
Adds conditioned links for the downstream CS docs to about-model-serving.
=> Link fixes: Adding cloud links to about-model-serving.

modules/ref-dashboard-configuration-options.adoc
ENG-17650: Updates the dashboard config options for 2.17
=> ENG-17650: Updates the dashboard config options for 2.17

modules/configuring-quota-management-for-distributed-workloads.adoc, modules/configuring-the-training-job.adoc, modules/downloading-the-demo-notebooks-from-the-codeflare-sdk.adoc, modules/enforcing-lqlabel-some.adoc, modules/installing-the-distributed-workloads-components.adoc, modules/managing-ray-clusters-from-within-a-jupyter-notebook.adoc, modules/monitoring-the-training-job.adoc, modules/overview-of-kueue-resources.adoc, modules/running-distributed-data-science-workloads-disconnected-env.adoc, modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, modules/running-the-demo-notebooks-from-the-codeflare-sdk.adoc, modules/running-the-training-job.adoc, modules/troubleshooting-common-problems-with-distributed-workloads-for-administrators.adoc, modules/viewing-kueue-alerts-for-distributed-workloads.adoc
Updates some downstream links to align with latest docs structure of Managing OAI > Managing DW content.
=> Pre-release link checks and fixes (2)

managing-odh.adoc
ENG-19897: Adds AMD and Gaudi info
=> ENG-19897: Adds AMD and Gaudi info

modules/configuring-custom-namespaces.adoc, modules/installing-the-odh-operator-v2.adoc
Addresses previously discovered formatting and style issues.
=> Addressing previously discovered formatting issues

modules/overview-of-kueue-resources.adoc
Fixing broken link
Local build
=> RHOAIENG-16783: fixing broken link

modules/deploying-models-on-the-single-model-serving-platform.adoc
=> RHOAIENG-14622_rev2-Few more updates

modules/lmeval-evaluation-job.adoc, modules/lmeval-scenarios.adoc
=> Lm eval 1-line update

modules/configuring-the-model-registry-component.adoc
Adds conditioned content to the _Configuring the model registry component module_ to cover the differences between SM and cloud.
=> ENG-17053: Downstream changes for cloud

modules/ref-dashboard-configuration-options.adoc
ENG-20052: Updates dashboard config options for 2.18
=> ENG-20052: Updates dashboard config options for 2.18

modules/about-base-training-images.adoc, modules/creating-a-custom-training-image.adoc, modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, modules/running-the-demo-notebooks-from-the-codeflare-sdk.adoc
ENG-18672+19598: Updates image info to make more general, so that we don't have to update each time a new image is provided
=> ENG-18672+19598: Updates image info to make more general

modules/disabling-applications-connected.adoc, modules/enabling-applications-connected.adoc, modules/next-steps-getting-started.adoc, working-with-connected-applications.adoc
Removes several references to Anaconda from the docs.
=> ENG-21134: Removing references to Anaconda.

assemblies/managing-distributed-workloads.adoc, modules/overview-of-distributed-workloads.adoc
ENG-18038: Adds note about OpenShift/Kueue compatibility issue
=> ENG-18038: Adds note about OpenShift/Kueue compatibility issue

assemblies/serving-large-models.adoc, modules/deploying-a-grafana-metrics-dashboard.adoc
Adding grafana metrics module from ai-on-openshift
Local build
=> RHOAIENG-17242: Adding grafana metrics module from ai-on-openshift

modules/creating-a-bias-metric-using-cli.adoc
One line update to code example instances from Liming Tsai in slack here: https://redhat-internal.slack.com/archives/C04AR71PEKE/p1741360942860549 forum-openshift-trusty-ai
=> SlackRequest_instances of 1 line of code updated

modules/deploying-a-grafana-metrics-dashboard.adoc
Addressing QE feedback: Adding a line in the procedure to indicate the origin of the overlay
Local build
=> RHOAIENG-17242: Addressing QE feedback

modules/guardrails-orchestrator-deployment.adoc, modules/guardrails-orchestrator-optional-config-otel.adoc, modules/guardrails-orchestrator-parameters.adoc
https://issues.redhat.com/browse/RHOAIENG-21420
https://issues.redhat.com/browse/RHOAIENG-13172
Modules to be included here: https://github.com/opendatahub-io/opendatahub-documentation/pull/676/files#diff-7fc6394c7329be9d476fd3c963356ab2d44d4338c5f0f61b339947a450927598R1
=> RHOAIENG-21420: Adding configuration modules for Guardrails orchestrator

modules/enabling-accelerators.adoc
This PR changes the title of the "Enabling Accelerators" module to sentence case.
=> ENG-20217 - corrected enabling accelerators title

assemblies/guardrails-orchestrator-service.adoc
ENG-16204 - Fixing small mistake
=> ENG-16204 - Fixing small mistake

modules/troubleshooting-dspa-component-errors.adoc
This PR corrects some problems and upstream vs downstream code discrepancies with the DSPA troubleshooting table.
=> Correcting discrepancy in dspa troubleshooting table code

modules/overview-of-pipeline-runs.adoc, modules/viewing-pipeline-artifacts.adoc
Added references to original run and original execution on the artifact detail page
=> RHOAI-17222 artifact detail page

modules/ref-inference-endpoints.adoc
Fixing path as per doc bug
Local build
=> RHOAIENG-19905: Fixing path 

modules/guardrails-orchestrator-parameters.adoc
Update to address post release tweaks
=> Jira 16204-Guardrails - Update to address post release tweaks

modules/adding-a-ca-bundle-after-upgrading.adoc, modules/installing-the-odh-operator-v2.adoc, modules/intel-gaudi-ai-accelerator-integration.adoc, modules/migrating-to-data-science-pipelines-2.adoc, modules/overview-of-accelerators.adoc, modules/overview-of-data-science-pipelines-caching.adoc, modules/requirements-for-upgrading-odh-v2.adoc, modules/working-with-accelerator-profiles.adoc, working-in-your-data-science-ide.adoc
Updated "support" statements for accuracy.
=> RHOAI-9849 support statements

modules/archiving-a-pipeline-experiment.adoc
Providing clarity around archiving your pipeline experiments, including when and how to delete them.
=> RHOAIENG-13292: Improve Archiving a pipeleine experiment text

api-workbench.adoc, modules/api-custom-image-creating.adoc, modules/api-workbench-creating.adoc, modules/api-workbench-overview.adoc
[RHOAIENG-19474](https://issues.redhat.com/browse/RHOAIENG-19474)
Adding a user guide for creating a Workbench and a custom image by using CRDs.
[Creating a Workbench Preview](https://shdeshpa07.github.io/Previews/RHOAI-Documentation/RHOAIENG-19474/api-workbench.html)
@CFSNM has validated the YAML files.
=> RHOAIENG-19474 Workbench user guide

assemblies/monitoring-data-drift.adoc, assemblies/monitoring-model-bias.adoc, assemblies/using-explainability.adoc, modules/creating-a-bias-metric-using-cli.adoc, modules/creating-a-bias-metric-using-dashboard.adoc, modules/creating-a-bias-metric.adoc, modules/creating-a-drift-metric.adoc, modules/duplicating-a-bias-metric.adoc, modules/lmeval-evaluation-job.adoc, modules/requesting-a-lime-explanation.adoc, modules/requesting-a-shap-explanation.adoc, modules/using-bias-metrics.adoc, modules/using-drift-metrics.adoc, modules/using-explainers.adoc
Titles and other instances updated to replace the word 'support'.
=> Updates to 'support' instances in the TrustyAI remit

modules/adding-a-custom-model-serving-runtime-for-the-multi-model-serving-platform.adoc, modules/adding-a-custom-model-serving-runtime-for-the-single-model-serving-platform.adoc, modules/adding-a-tested-and-verified-runtime-for-the-multi-model-serving-platform.adoc, modules/adding-a-tested-and-verified-runtime-for-the-single-model-serving-platform.adoc, modules/configuring-a-recommended-accelerator-for-serving-runtimes.adoc, modules/configuring-the-operator-logger.adoc, modules/customizing-component-resources.adoc, modules/disabling-component-resource-customization.adoc, modules/reenabling-component-resource-customization.adoc, modules/resolving-cuda-oom-errors.adoc
Menu arrow format fix, and testing cherry picking steps.
=> Arrow fix and cherry-pick test

modules/adding-a-custom-model-serving-runtime-for-the-multi-model-serving-platform.adoc, modules/adding-a-custom-model-serving-runtime-for-the-single-model-serving-platform.adoc, modules/adding-a-tested-and-verified-runtime-for-the-multi-model-serving-platform.adoc, modules/adding-a-tested-and-verified-runtime-for-the-single-model-serving-platform.adoc, modules/configuring-a-recommended-accelerator-for-serving-runtimes.adoc, modules/configuring-the-operator-logger.adoc, modules/customizing-component-resources.adoc, modules/disabling-component-resource-customization.adoc, modules/reenabling-component-resource-customization.adoc, modules/resolving-cuda-oom-errors.adoc
Arrow format fix, cherry pick to v2.18 to test steps
=> Arrow fix and cherry-pick test (#697)

modules/overview-of-model-monitoring.adoc
1. Updated the concept module to incl LM Eval and Gorch products; 
2. Added sentence to group the different services.
=> Update to include statements on LMEval and Gorch downstream

assemblies/configuring-the-guardrails-orchestrator-service.adoc, modules/configuring-the-opentelemetry-exporter.adoc, modules/deploying-the-guardrails-orchestrator-service.adoc, modules/guardrails-orchestrator-parameters.adoc
Addressed QE feedback contained in https://issues.redhat.com/browse/RHOAIENG-21890
=> RHOAIENG-21890:Addressing formatting issues post-release

modules/configuring-monitoring-for-your-model-serving-platform.adoc
Removing duplicated content and adding upstream and downstream links instead.
=> Removing duplicated content and adding links instead

modules/ref-dashboard-configuration-options.adoc, modules/viewing-project-metrics-for-distributed-workloads.adoc, modules/viewing-the-status-of-distributed-workloads.adoc
Updates references to the Distributed workloads nav menu item.
=> ENG-20539: Updating refs to DW nav menu item.

modules/archiving-a-model-version.adoc, modules/archiving-a-model.adoc, modules/creating-a-model-registry.adoc, modules/deleting-a-deployed-model-version-from-a-model-registry.adoc, modules/deleting-a-model-registry.adoc, modules/deploying-a-model-version-from-a-model-registry.adoc, modules/editing-a-model-registry.adoc, modules/editing-model-metadata-in-a-model-registry.adoc, modules/editing-model-version-metadata-in-a-model-registry.adoc, modules/editing-the-deployment-properties-of-a-model-deployed-by-using-the-multi-model-serving-platform.adoc, modules/editing-the-deployment-properties-of-a-model-deployed-by-using-the-single-model-serving-platform.adoc, modules/ref-dashboard-configuration-options.adoc, modules/registering-a-model-version.adoc, modules/registering-a-model.adoc, modules/restoring-a-model-version.adoc, modules/restoring-a-model.adoc, modules/viewing-registered-model-versions.adoc, modules/viewing-registered-models.adoc
Updates references to the 'Model Registry' nav item and page to use the updated nav menu structure. (**Models > Model registry**).
=> ENG-20540: Updating references to Model Registry nav menu item/page

modules/creating-a-custom-training-image.adoc
ENG-21150: Adds Ray ROCm Python 3.9 image
=> ENG-21150: Adds Ray ROCm Python 3.9 image

modules/api-workbench-creating.adoc, modules/viewing-installed-components.adoc
fixing links found in preview test
=> fixing links

modules/accessing-inference-endpoint-for-model-deployed-on-single-model-serving-platform.adoc, modules/archiving-a-model-version.adoc, modules/archiving-a-model.adoc, modules/creating-a-bias-metric-using-dashboard.adoc, modules/customizing-parameters-serving-runtime.adoc, modules/deleting-a-bias-metric-using-dashboard.adoc, modules/deleting-a-deployed-model.adoc, modules/deploying-a-model-using-the-multi-model-serving-platform.adoc, modules/deploying-models-on-the-NVIDIA-NIM-model-serving-platform.adoc, modules/deploying-models-on-the-single-model-serving-platform.adoc, modules/duplicating-a-bias-metric.adoc, modules/ref-dashboard-configuration-options.adoc, modules/resolving-cuda-oom-errors.adoc, modules/updating-the-deployment-properties-of-a-deployed-model.adoc, modules/viewing-a-deployed-model.adoc, modules/viewing-bias-metrics.adoc, modules/viewing-http-request-metrics-for-a-deployed-model.adoc
Model serving UI updates:
*Model serving* to *Models*
*Deployed models* to *Model deployments*
Local build
=> RHOAIENG-20541: Model serving UI updates

assemblies/serving-large-models.adoc, modules/deploying-model-stored-in-oci-image-cli.adoc, modules/deploying-models-on-the-single-model-serving-platform.adoc, modules/using-oci-containers-for-model-storage.adoc
GA for model cars
Additions to this topic: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2.18/html/serving_models/serving-large-models_serving-large-models#deploying-models-on-the-single-model-serving-platform_serving-large-models
(truncated screenshot)
Created local preview with gatbsy and confirmed changes appeared as expected
=> RHOAIENG-13399 - Deploying models in OCI container images (Model cars) GA

modules/ref-dashboard-configuration-options.adoc
ENG-20053: Updates dashboard config options for 2.19
=> ENG-20053: Updates dashboard config options for 2.19

modules/configuring-quota-management-for-distributed-workloads.adoc, modules/installing-the-distributed-workloads-components.adoc, modules/ref-example-kueue-resource-configurations.adoc, modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, modules/running-the-demo-notebooks-from-the-codeflare-sdk.adoc
ENG-22656: Reinserts info that was mistakenly removed
=> ENG-22656: Reinserts info that was mistakenly removed

modules/about-kserve-deployment-modes.adoc
=> Fix to minor wording in KServe raw content

modules/lmeval-scenarios.adoc
ENG-22466 - S3 Storage LMEval documentation
=> ENG-22466 - S3 Storage LMEval documentation

modules/adding-a-custom-model-serving-runtime-for-the-single-model-serving-platform.adoc, modules/customizable-model-serving-runtime-parameters.adoc, modules/ref-inference-endpoints.adoc, modules/ref-supported-runtimes.adoc, modules/resolving-cuda-oom-errors.adoc
Deprecation note for TGIS
Local build
=> RHOAIENG-20960: Deprecation note for TGIS

modules/lmeval-scenarios.adoc, modules/setting-up-lmeval.adoc
Updating a numbered list
Updating Config Map
=> ENG-23162_ConfigMapUpdate 

assemblies/configuring-the-guardrails-orchestrator-service.adoc, modules/guardrails-orchestrator-hap-scenario.adoc
https://issues.redhat.com/browse/RHOAIENG-22480
=> RHOAIENG-22480: Adding Guardrails Orchestrator use case examples

modules/deploying-a-model-using-the-multi-model-serving-platform.adoc, modules/deploying-models-on-the-single-model-serving-platform.adoc
Adds notes to the single and multi-model deployment to highlight conditional pre-filling behaviour for data connections with registered models.
=> Adding MR connection notes to model deployment procs.

modules/configuring-a-cluster-for-rdma.adoc, modules/configuring-a-multi-node-pytorch-training-job-for-rdma.adoc, modules/enabling-multi-node-pytorch-training-jobs-with-rdma.adoc, modules/enabling-nvidia-gpus.adoc, modules/installing-the-distributed-workloads-components.adoc
ENG-19266: Adds new modules for multinode PyTorch RDMA
=> ENG-19266: Adds new modules for multinode PyTorch RDMA

working-with-distributed-workloads.adoc
ENG-16140: Updates the included KFTO assembly
=> ENG-16140: Updates the included KFTO assembly

assemblies/configuring-the-guardrails-orchestrator-service.adoc, modules/deploying-the-guardrails-orchestrator-service.adoc, modules/guardrails-orchestrator-configuring-regex-vllm-gateway.adoc, modules/guardrails-orchestrator-hap-scenario.adoc, modules/guardrails-orchestrator-parameters.adoc, modules/guardrails-orchestrator-regex-using.adoc, modules/guardrails-orchestrator-vllm-gateway-using.adoc
https://issues.redhat.com/browse/RHOAIENG-22473
=> RHOAIENG-22473:Docs for configuring regex detector

modules/guardrails-orchestrator-vllm-gateway-using.adoc
=> fixing preview issues

modules/migrating-to-data-science-pipelines-2.adoc
=> Altering pipelines migration doc to cover latest workbench image release

modules/about-base-training-images.adoc, modules/configuring-a-training-job-by-using-the-kfto-sdk.adoc, modules/configuring-the-fine-tuning-job.adoc, modules/configuring-the-model-registry-component.adoc, modules/creating-a-custom-training-image.adoc, modules/creating-a-kfto-pytorch-training-script-configmap-resource.adoc, modules/creating-a-kfto-pytorchjob-resource-by-using-the-cli.adoc, modules/creating-a-kfto-pytorchjob-resource.adoc, modules/creating-a-workbench-for-distributed-training.adoc, modules/enabling-nvidia-gpus.adoc, modules/ref-example-dockerfile-for-a-kfto-pytorch-training-script.adoc, modules/running-a-training-job-by-using-the-kfto-sdk.adoc, modules/running-the-demo-notebooks-from-the-codeflare-sdk.adoc
=> RHOAIENG-20923: fixing broken links

modules/configuring-a-training-job-by-using-the-kfto-sdk.adoc, modules/creating-a-kfto-pytorchjob-resource-by-using-the-cli.adoc, modules/creating-a-workbench-for-distributed-training.adoc, modules/deleting-the-fine-tuning-job.adoc, modules/running-the-demo-notebooks-from-the-codeflare-sdk.adoc, modules/running-the-fine-tuning-job.adoc
=> RHOAIENG-20923_rev1: few more broken links

assemblies/serving-large-models.adoc, modules/deploying-models-on-the-single-model-serving-platform.adoc, modules/model-serving-runtimes.adoc, modules/ref-supported-runtimes.adoc
As part of the GA updates to KServe raw, add a prerequisite that explains vLLM/Power&Z limitations as described in the following Google doc:
https://docs.google.com/document/d/18QriyMIW93_Xg3apCFS7Dmj5dnFPMLOtzt1Z1SfVtFE/edit?tab=t.145rb8pwnccb#heading=h.ws2hunisx8gg
Jira ticket: https://issues.redhat.com/browse/RHOAIENG-22688
=> ENG-22688: Add Power/Z prerequisite to KServe raw documentation

modules/uploading-training-data-to-trustyai.adoc
=> Fixes downstream extra space in link

modules/adding-a-connection-to-your-data-science-project.adoc
Add update to add connection page to reflect OCI container option
Built local gatsby build and verified changes appeared as expected
=> Add update to add connection page to reflect OCI container option

assemblies/preparing-the-distributed-training-environment.adoc, modules/configuring-a-cluster-for-rdma.adoc, modules/configuring-a-training-job-by-using-the-kfto-sdk.adoc, modules/creating-a-custom-training-image.adoc, modules/creating-a-kfto-pytorch-training-script-configmap-resource.adoc, modules/creating-a-kfto-pytorchjob-resource-by-using-the-cli.adoc, modules/creating-a-kfto-pytorchjob-resource.adoc, modules/creating-a-multi-node-pytorch-training-job-with-rdma.adoc, modules/creating-a-workbench-for-distributed-training.adoc, modules/downloading-the-demo-notebooks-from-the-codeflare-sdk.adoc, modules/enforcing-lqlabel-some.adoc, modules/installing-the-distributed-workloads-components.adoc, modules/managing-ray-clusters-from-within-a-jupyter-notebook.adoc, modules/overview-of-kueue-resources.adoc, modules/ref-example-kueue-resource-configurations.adoc, modules/running-distributed-data-science-workloads-from-ds-pipelines.adoc, modules/running-the-demo-notebooks-from-the-codeflare-sdk.adoc, modules/running-the-fine-tuning-job.adoc, modules/viewing-kueue-alerts-for-distributed-workloads.adoc
ENG-24252: Fixes broken links in 2.19 DW doc
=> ENG-24252: Fixes broken links in 2.19 DW doc

modules/deploying-models-using-multiple-gpu-nodes.adoc
Adjusted the value of a parameter for accuracy
=> Fix parameter value

modules/configuring-the-model-registry-component.adoc
Updates a prereq in the 'Configuring the MR component' module to reflect latest Authorino operator requirement.
=> ENG-16613: Updating Authorino req in MR configuration steps.

modules/starting-a-jupyter-notebook-server.adoc
See https://issues.redhat.com/browse/RHOAIENG-17147
=> ENG-17147: Removing Authorize Access references

modules/requirements-for-upgrading-odh-v2.adoc
ENG-24407: Updates upgrade requirements to add kueue entry
=> ENG-24407: Updates upgrade requirements to add kueue entry

modules/model-serving-runtimes.adoc
Small update to inference service example
Local build
=> RHOAIENG-24233: Updating runtime value for inference service example

modules/adding-a-model-server-for-the-multi-model-serving-platform.adoc, modules/creating-a-project-workbench.adoc, modules/deploying-models-on-the-NVIDIA-NIM-model-serving-platform.adoc, modules/deploying-models-on-the-single-model-serving-platform.adoc, modules/updating-a-model-server.adoc, modules/working-with-hardware-profiles.adoc
I have added further information on the dependencies relating to hardware profiles when using the UI in the dashboard. I have also correct a broken ODH link by adding an upstream equivalent, and correcting a typo in an asciidoc condition.
=> Eng 24180 hardware profiles docs enhancements

modules/overview-of-features-and-feature-store.adoc
in one file, correct attribute typo product-name > productname
=> odh-23179 fix typo in attribute

assemblies/configuring-trustyai.adoc, modules/enabling-trustyai-kserve-integration.adoc
Small module added to show how to integrate KServe RawDeployment.
=> Small module added to show how to integrate KServe RawDeployment

modules/creating-a-custom-training-image.adoc, modules/creating-a-kfto-pytorchjob-resource.adoc, modules/creating-a-multi-node-pytorch-training-job-with-rdma.adoc, modules/ref-example-dockerfile-for-a-kfto-pytorch-training-script.adoc, modules/ref-example-kfto-pytorchjob-resource-configured-to-run-with-rdma.adoc, modules/ref-example-kfto-pytorchjob-resource-for-multi-node-training.adoc, modules/running-a-training-job-by-using-the-kfto-sdk.adoc, modules/running-the-fine-tuning-job.adoc
ENG-24314: Updates the latest KFTO image versions
=> ENG-24314: Updates the latest KFTO image versions

assemblies/serving-large-models.adoc, modules/deploying-vllm-gpu-metrics-dashboard-grafana.adoc, modules/ref-accelerator-metrics.adoc, modules/ref-cpu-metrics.adoc, modules/ref-grafana-metrics.adoc, modules/ref-vllm-metrics.adoc
Add reference containing grafana metrics
Built local preview and confirmed changes appeared as expected
=> Grafana metrics

assemblies/configuring-trustyai.adoc, modules/enabling-trustyai-kserve-integration.adoc
Updating typo- KServe Integration
=> Updating typo- KServe Integration

assemblies/customizing-the-dashboard.adoc, managing-odh.adoc, modules/editing-the-dashboard-configuration-file.adoc, modules/editing-the-dashboard-configuration.adoc, modules/enabling-custom-images.adoc, modules/hiding-information-about-applications.adoc, modules/importing-a-custom-workbench-image.adoc, modules/preventing-users-from-adding-applications-to-the-dashboard.adoc, modules/ref-dashboard-configuration-options.adoc
… to clarify that you need to add the entry
=> ENG-23476: Adds 2.20 dashboard config options; ENG-25022: Clarifies disableHardwareProfiles entry

assemblies/working-with-model-registries.adoc, modules/deploying-a-model-from-the-model-catalog.adoc, modules/enabling-the-model-catalog.adoc, modules/overview-of-model-registries.adoc, modules/registering-a-model-from-the-model-catalog.adoc, modules/registering-a-model-version.adoc, modules/registering-a-model.adoc, working-with-model-registries.adoc
Adds content for the tech preview model catalog release, updates notes on deploying models registered from URIs.
- new module for enabling the model catalog
- new modules for registering and deploying models from the catalog
- update to the model registry overview
=> 18453: TP model catalog changes

modules/enabling-the-model-catalog.adoc
Corrects the text in a step in the Enabling MC proc.
=> Enabling MC - corrects link bullet

assemblies/configuring-the-guardrails-orchestrator-service.adoc, modules/deploying-the-guardrails-orchestrator-service.adoc, modules/guardrails-orchestrator-parameters.adoc
=> Update to GO parameters

modules/ref-dashboard-configuration-options.adoc
ENG-23476: Updates Dashboard Config Options based on QA feedback
=> ENG-23476: Updates Dashboard Config Options based on QA feedback

assemblies/customizing-your-feature-store-configuration.adoc, modules/configuring-an-offline-store.adoc, modules/configuring-an-online-store.adoc, modules/viewing-feature-store-objects-in-the-web-based-ui.adoc
update Feature Store based on SME review comments
=> odh-23179-c SME review comments

modules/deploying-teacher-and-judge-models.adoc, modules/using-lab-tuning.adoc
- Added /v1 format to teacher/judge model endpoint from https://github.com/opendatahub-io/opendatahub-documentation/pull/775#discussion_r2089334436
- Reworded step from another suggestion
=> RHOAI-16971 endpoint format

modules/configuring-custom-namespaces.adoc, modules/overview-of-enabling-lab-tuning.adoc
=> fixing typo

modules/enabling-nvidia-gpus.adoc, modules/installing-the-distributed-workloads-components.adoc
ENG-25528: Updates RDMA note to remove confusion
=> ENG-25528: Updates RDMA note to remove confusion

modules/enabling-nvidia-gpus.adoc, modules/installing-the-distributed-workloads-components.adoc
ENG-25528: Updates RDMA note in cloud text
=> ENG-25528: Updates RDMA note in cloud text

modules/guardrails-orchestrator-configuring-regex-guardrails-gateway.adoc
=> Updated YAML for GOrch

modules/enabling-trustyai-kserve-integration.adoc
=> Update to edit module ID name

modules/deploying-a-model-from-the-model-catalog.adoc, modules/deploying-a-model-version-from-a-model-registry.adoc, modules/enabling-the-model-catalog.adoc, modules/overview-of-model-registries.adoc, modules/registering-a-model-from-the-model-catalog.adoc
- Adds a link to the LAB-tuning documentation from the MR overview.
- Adds conditions to the 'disconnected' MC note, displaying for only upstream and SM.
=> 18453: Link and condition updates

modules/overview-of-features-and-feature-store.adoc
remove reference to data transformation being a task done before using Feature Store
=> 23179 update Feature store overview

modules/overview-of-features-and-feature-store.adoc
small update as per SME request
=> 23179 update Feature store overview (#791)

modules/adding-a-custom-model-serving-runtime-for-the-multi-model-serving-platform.adoc, modules/creating-a-custom-image-from-your-own-image.adoc, modules/troubleshooting-common-problems-with-distributed-workloads-for-users.adoc
Removed contractions
Created local gatsby build and verified that the changes appeared as expected
=> Remove contractions

modules/creating-a-model-registry-for-lab-tuning.adoc, modules/installing-the-required-components-for-lab-tuning.adoc
Moved note into relevant section
=> Moved model registry permissions info for LAB-tuning

modules/duplicating-a-scheduled-pipeline-run.adoc, modules/scheduling-a-pipeline-run.adoc
Add option to use latest pipeline version in scheduled runs
=> RHOAI-21758 use latest pipeline version in scheduled runs

modules/creating-a-model-registry.adoc, modules/editing-a-model-registry.adoc
Removes duplicate prereq content in 2 model registry modules.
@coderabbitai ignore
=> Remove duplicate MR prereqs

modules/configuring-monitoring-for-the-single-model-serving-platform.adoc, modules/deploying-a-llama-model-with-kserve.adoc, modules/deploying-a-model-from-the-model-catalog.adoc, modules/deploying-a-model-version-from-a-model-registry.adoc, modules/enabling-metrics-for-existing-nim-deployment.adoc, modules/model-serving-runtimes-for-accelerators.adoc
Few more model serving link fixes
=> Few more link fixes

modules/installing-the-distributed-workloads-components.adoc
=> Kueue edit - cherry pick 972 to v2.24
